var h=(a,b)=>{if(!b.has(a))throw TypeError("Cannot read from private field");return b.get(a)},n=(a,b,c)=>{if(b.has(a))throw TypeError("Cannot add the same private member more than once");b instanceof WeakSet?b.add(a):b.set(a,c)},q=(a,b,c)=>{if(!b.has(a))throw TypeError("Cannot write to private field");b.set(a,c)},u=(a,b,c)=>{if(!b.has(a))throw TypeError("Cannot access private method");return c},aa=(a,b)=>({set Y(c){q(a,b,c)},get Y(){return h(a,b)}});
(function(){function a(c){if(!c.Ca){c.Ca=!0;var d={};d=(c.integrity&&(d.integrity=c.integrity),c.referrerPolicy&&(d.referrerPolicy=c.referrerPolicy),c.crossOrigin==="use-credentials"?d.credentials="include":c.crossOrigin==="anonymous"?d.credentials="omit":d.credentials="same-origin",d);fetch(c.href,d)}}const b=document.createElement("link").relList;if(!(b&&b.supports&&b.supports("modulepreload"))){for(const c of document.querySelectorAll('link[rel="modulepreload"]'))a(c);(new MutationObserver(c=>
{for(const d of c)if(d.type==="childList")for(const e of d.addedNodes)e.tagName==="LINK"&&e.rel==="modulepreload"&&a(e)})).observe(document,{childList:!0,subtree:!0})}})();const z={J:342,I:192,Aa:10,za:1,oa:42,na:4,pa:.02,Ia:0,Ha:1,La:!0,Ka:!1,xa:16.667,X:25};function ba(a){a=[...a];for(let b=a.length-1;b>0;b--){const c=Math.floor(Math.random()*(b+1));[a[b],a[c]]=[a[c],a[b]]}return a}
function ca(a){var b=Math.max(10,Math.min(a,80));const c=b*Math.PI/180;a=[];(a.push([{dx:0,dy:-1}]),b<50)?(a.push([{dx:1,dy:-1},{dx:-1,dy:-1}]),b=Math.round(1/Math.tan(c)),a.push([{dx:b,dy:-1},{dx:b*-1,dy:-1}])):(b=Math.round(Math.tan(c)),a.push([{dx:1,dy:-b},{dx:-1,dy:-b}]));return a}
async function da(){try{const a=await fetch("./src/data/particles.data");if(!a.ok)throw Error(`HTTP error! Status: ${a.status}`);return await a.text()}catch(a){throw console.error("Failed to read particle data from ./src/data/particles.data:",a),Error("Failed to load particle data.");}}
async function ea(){var a=await da();let b={};var c=new Set,d=null;for(var e of a.split("\n"))if(a=e.trim(),a.length!==0&&!a.startsWith("#"))if(a.startsWith("[")&&a.endsWith("]"))a=parseInt(a.slice(1,-1),10),isNaN(a)||a<10?d=null:c.has(a)?(console.warn(`[Loader] Duplicate ID found: ${a}. Ignoring.`),d=null):(c.add(a),d=a,b[a]={});else if(d!==null&&(a=a.split(":").map(g=>g.trim()),a.length===2)){const g=a[1],f=b[d];switch(a[0]){case "name":f.name=g;break;case "category":f.h=parseInt(g,10);break;case "base_color":f.fa=
g;break;case "variant_color":f.la=g;break;case "is_movable":f.ha=g==="true";break;case "density":f.A=parseFloat(g);break;case "max_concentration":f.Ea=parseInt(g);break;case "repose_angle":f.ka=parseFloat(g)}}c={};for(const g in b)d=b[g],e=parseInt(g,10),d.name===void 0||d.h===void 0||d.fa===void 0||d.la===void 0||d.ha===void 0||d.A===void 0?console.warn(`[Loader] Corrupted particle block found of ID: ${e}. Missing core properties.`):(a={id:e,name:d.name,aa:d.fa,da:d.la,U:d.ha,A:d.A},d.h===1?c[e]=
{...a,h:1}:d.h===2?c[e]={...a,ia:d.Ea,h:2}:d.h===3?c[e]={...a,h:3}:d.h===4?c[e]={...a,h:4,ja:d.ka,ba:ca(d.ka)}:d.h===5&&(c[e]={...a,h:5}));return c[0]={id:0,name:"Empty",h:0,aa:"#0E0E11",da:"#0E0E11",U:!0,A:0},c}var A,fa,ha,ia;
class ja{constructor(a){n(this,A);this.g=a;this.i=this.g.getContext("2d");this.P=z.J;this.O=z.I;this.N=new Uint8ClampedArray(this.P*this.O*4);this.Z=[];this.j=[];this.$=[];this.g.width=this.P;this.g.height=this.O;this.i.imageSmoothingEnabled=!1;this.i.translate(0,this.g.height);this.i.scale(1,-1)}}A=new WeakSet;
fa=function(){var a=this.Z;const b=this.P,c=this.O;for(const d of a){a=(c-1-d.position.y)*b+d.position.x;let e=u(this,A,ha).call(this,d);this.N[a*4]=e[0];this.N[a*4+1]=e[1];this.N[a*4+2]=e[2];this.N[a*4+3]=e[3]}};ha=function(a){return a.color};ia=function(a,b){for(const {index:d,value:e}of b){var c=e[3];b=c/255;const g=Math.round(e[1]*b+a[d*4+1]*(1-b)),f=Math.round(e[2]*b+a[d*4+2]*(1-b));c=Math.min(a[d*4+3],c);a[d*4]=Math.round(e[0]*b+a[d*4]*(1-b));a[d*4+1]=g;a[d*4+2]=f;a[d*4+3]=c}};
const ka=Object.freeze({Xa:new Uint8ClampedArray([255,255,255,255]),ea:new Uint8ClampedArray([0,0,0,255]),Pa:new Uint8ClampedArray([128,128,128,255]),RED:new Uint8ClampedArray([255,0,0,255]),Qa:new Uint8ClampedArray([0,255,0,255]),Ga:new Uint8ClampedArray([0,0,255,255]),Ya:new Uint8ClampedArray([255,255,0,255]),Ja:new Uint8ClampedArray([0,255,255,255]),Ra:new Uint8ClampedArray([255,0,255,255]),Ua:new Uint8ClampedArray([0,0,0,0]),Ta:new Uint8ClampedArray([255,255,255,128])});
function B(a){if(a==null)return ka.ea;a=a.replace("#","");if(a.length===6)a+="FF";else if(a.length===3){let c="";for(var b of a)c+=b,c+=b;a=c+"FF"}else return ka.ea;b=parseInt(a,16);return new Uint8ClampedArray([b>>24&255,b>>16&255,b>>8&255,b&255])}function la(a){return.299*a[0]+.587*a[1]+.114*a[2]}
const ma=Object.freeze({ma:[{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1},{dx:-1,dy:0},{dx:1,dy:0},{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1}]}),na=Object.freeze({Va:{dx:-1,dy:1},Ba:{dx:0,dy:1},Wa:{dx:1,dy:1},qa:{dx:-1,dy:0},Sa:{dx:1,dy:0},Na:{dx:-1,dy:-1},Ma:{dx:0,dy:-1},Oa:{dx:1,dy:-1}});var C,E,F,oa,pa;function G(a,b){h(a,E).add(b.index);b=qa(a,b);for(const c of b)h(a,E).add(c.index)}function ra(a,b,c){return b>=0&&b<a.width&&c>=0&&c<a.height?h(a,C)[c*a.width+b]:null}
function sa(a,b,c,d=!1){for(var e of c)if(e){c=ba(e);for(const g of c)if(c=g.dx,d&&Math.random()>.5&&(c=g.dx*-1),(c=ra(a,b.position.x+c,b.position.y+g.dy))&&c.U&&b.A>c.A)return h(a,C)[c.index]=b,h(a,C)[b.index]=c,d={x:b.position.x,y:b.position.y},e=b.index,b.position=c.position,b.index=c.index,c.position=d,c.index=e,G(a,b),G(a,c),c}return null}
function ta(a,b,c){h(a,C)[b.index]=c;h(a,C)[c.index]=b;const d={x:b.position.x,y:b.position.y},e=b.index;b.position=c.position;b.index=c.index;c.position=d;c.index=e;G(a,b);G(a,c)}function ua(a,b,c){return ra(a,b.position.x+c.dx,b.position.y+c.dy)}function qa(a,b){return ma.ma.map(c=>ua(a,b,c)).filter(c=>c!==null).filter(()=>!0)}
class va{constructor(a,b,c){n(this,F);n(this,C);n(this,E);this.width=a;this.height=b;q(this,C,Array(a*b));q(this,E,new Set);this.va=c;u(this,F,pa).call(this,0)}get data(){return h(this,C)}get ga(){return h(this,E)}}C=new WeakMap;E=new WeakMap;F=new WeakSet;
oa=function(a){a=this.va[a];if(!a)return null;var b=Math.round(Math.random()*5)/5;const c=B(a.aa),d=B(a.da);b=new Uint8ClampedArray([c[0]+(d[0]-c[0])*b,c[1]+(d[1]-c[1])*b,c[2]+(d[2]-c[2])*b,c[3]+(d[3]-c[3])*b]);b={handle:-1,id:a.id,name:a.name,color:b,position:{x:-1,y:-1},index:0,U:a.U,A:a.A};return a.h===0?{...b,h:0}:a.h===1?{...b,h:1}:a.h===2?{...b,h:2,Za:0,ia:a.ia}:a.h===3?{...b,h:3}:a.h===4?{...b,h:4,ja:a.ja,ba:a.ba}:a.h===5?{...b,h:5,node:-1}:null};
pa=function(a){const b=this.width,c=this.height;q(this,C,Array(b*c));for(let d=0;d<c;d++)for(let e=0;e<b;e++){let g=d*b+e,f=u(this,F,oa).call(this,a);f&&(f.position.x=e,f.position.y=d,f.index=g,h(this,C)[g]=f,h(this,E).add(f.index))}};const wa=Object.keys(na);var H,xa,I,ya,za,J,K,L,Aa,Ba,M,N,O,P,Ca,Da,Q,Ea,Fa,Ga,Ha,Ia;
function Ja(a){const b=a.width;var c=a.height;const d=[],e=[],g={};for(--c;c>=0;c--)for(let t=0;t<b;t++){var f=c*b+t,k=ra(a,t,c);if(!k||k.h!==2||k.h!==2)continue;const p=ua(a,k,na.Ba);var m=ua(a,k,na.qa),l=p&&p.id===k.id;const w=m&&m.id===k.id;let x=-1;w&&(x=c*b+(t-1));let v=-1;l&&(v=(c+1)*b+t);m=p&&p.id===0;if(w||l)if(w&&!l)l=g[x],d[l].push(f),m&&(e[l].u.push(k),e[l].B.push(p)),g[f]=l;else if(!w&&l)l=g[v],d[l].push(f),m&&(e[l].u.push(k),e[l].B.push(p)),g[f]=l;else{if(l=g[v],d[l].push(f),m&&(e[l].u.push(k),
e[l].B.push(p)),g[f]=l,f=g[x],f!==l){k=e[f];for(const y of k.u)e[l].u.push(y);for(const y of k.B)e[l].B.push(y);k=d[f];for(const y of k)g[y]=l;d[f]=[];e[f]={u:[],B:[]}}}else l=e.length,d.push([f]),e.push({u:[],B:[]}),m&&(e[l].u.push(k),e[l].B.push(p)),g[f]=l}return e.filter(t=>t.u.length>30)}
class Ka{constructor(a,b,c,d){n(this,Q);n(this,H);n(this,xa);n(this,I);n(this,ya);n(this,za);n(this,J);n(this,K);n(this,L);n(this,Aa);n(this,Ba);n(this,M);n(this,N);n(this,O);n(this,P,0);n(this,Ca,60);n(this,Da,e=>{if(h(this,L)){if(h(this,N)){var g=e-h(this,N);q(this,N,e);var f=h(this,xa),k=h(this,J),m=h(this,H),l=Math.floor(f.o.x),t=Math.floor(f.o.y);if(f.H){var p=La(f,l,t);m.$=p}if(f.g||f.j)if(m=t<f.F+f.l&&t>=0-f.l,l<f.D+f.l&&l>=0-f.l&&m){--t;m=f.l;p=f.g?f.C:0;for(let S=-m;S<=m;S++)for(let T=-m;T<=
m;T++)if(!(S*S+T*T>m*m)){var w=l+S,x=t+T;if(w>=0&&w<k.width&&x>=0&&x<k.height){var v=ra(k,w,x);if(p===0||v===null||v.id===0){v=k;var y=p;w>=0&&w<v.width&&x>=0&&x<v.height&&(y=u(v,F,oa).call(v,y),y.position.x=w,y.position.y=x,y.index=x*v.width+w,G(v,y),h(v,C)[x*v.width+w]=y)}}}}f.T&&(k=f.l-f.G*f.sa,k=Math.floor(k),k=Math.min(f.ta,k),k=Math.max(0,k),f.l=k,f.G=0);q(this,O,h(this,O)+g);for(g=0;h(this,O)>=h(this,M);){l=[];for(var r of h(this,J).ga)l.push(h(this,J).data[r]);aa(this,P).Y++;h(this,P)>h(this,
Ca)&&(h(this,J).ga.clear(),q(this,P,0));t=new Uint8ClampedArray([210,55,55,180]);f=h(this,H);k=l;t=h(this,I).Da?t:void 0;if(f.Z.push(...k),t){m=f.P;p=f.O;for(var D of k)f.j.push({index:(p-1-D.position.y)*m+D.position.x,value:t})}u(this,Q,Ea).call(this,l);this.ca++;q(this,O,h(this,O)-h(this,M));g++;g>60&&q(this,O,0)}r=h(this,H);u(r,A,fa).call(r);D=new Uint8ClampedArray(r.N);u(r,A,ia).call(r,D,r.j);u(r,A,ia).call(r,D,r.$);D=new ImageData(D,r.P,r.O);r.i.putImageData(D,0,0);r.Z.length=0;r.j=[];r.$=[];
r=h(this,I);h(r,R)&&(u(r,Ma,Na).call(r,e,this),(e=h(r,U).get("fps"))&&(e.textContent=`FPS: ${h(r,V).toFixed(2)}`),(e=h(r,U).get("tps"))&&(e.textContent=`TPS: ${h(r,W).toFixed(2)}`))}else q(this,N,e);q(this,Aa,requestAnimationFrame(h(this,Da)))}});q(this,H,b);q(this,xa,c);q(this,I,d);q(this,ya,z.J);q(this,za,z.I);q(this,J,new va(h(this,ya),h(this,za),a));q(this,K,new Set);q(this,L,!1);q(this,Aa,null);q(this,Ba,z.xa);q(this,M,z.X);q(this,N,null);q(this,O,0);this.ca=0}start(){h(this,L)||(q(this,L,!0),
h(this,Da).call(this,0))}}H=new WeakMap;xa=new WeakMap;I=new WeakMap;ya=new WeakMap;za=new WeakMap;J=new WeakMap;K=new WeakMap;L=new WeakMap;Aa=new WeakMap;Ba=new WeakMap;M=new WeakMap;N=new WeakMap;O=new WeakMap;P=new WeakMap;Ca=new WeakMap;Da=new WeakMap;Q=new WeakSet;
Ea=function(a){h(this,K).clear();a=ba(a);a.sort((b,c)=>b.position.y-c.position.y);for(const b of a)if(b&&!h(this,K).has(b.index))switch(b.h){case 2:u(this,Q,Fa).call(this,b);break;case 3:u(this,Q,Ga).call(this,b);break;case 4:u(this,Q,Ha).call(this,b)}a=Ja(h(this,J));u(this,Q,Ia).call(this,a)};Fa=function(a){const b=sa(h(this,J),a,[[{dx:0,dy:-1}],[{dx:-1,dy:-1},{dx:1,dy:-1}],[{dx:-1,dy:0},{dx:1,dy:0}]],!1);b&&(h(this,K).add(a.index),h(this,K).add(b.index))};
Ga=function(a){var b=[[na[wa[Math.floor(Math.random()*wa.length)]]]];(b=sa(h(this,J),a,b,!1))&&(h(this,K).add(a.index),h(this,K).add(b.index))};Ha=function(a){var b=a.ba;(b=sa(h(this,J),a,b,!0))&&(h(this,K).add(a.index),h(this,K).add(b.index))};
Ia=function(a){for(const b of a){a=b.u.sort((f,k)=>k.position.y-f.position.y);const c=b.B.sort((f,k)=>f.position.y-k.position.y),d=a.length;let e=0;const g=d/4;for(let f=0;f<d;f++){const k=a[f],m=c[f];if(Math.sqrt(k.position.x*m.position.x+k.position.y*m.position.y),k.position.y>m.position.y&&(ta(h(this,J),k,m),h(this,K).add(k.index),h(this,K).add(m.index),e++,e>=g))break}}};
function Oa(a,b){var c=document.createElement("div");c.classList.add("ui-window");a.W.appendChild(c);a.g=c;a.g.style.left="320px";a.g.style.top="300px";a.g.style.width=`${a.M.width}px`;a.g.style.height=`${a.M.height}px`;a.g.style.maxWidth=`${a.K.width}px`;a.g.style.maxHeight=`${a.K.height}px`;c=document.createElement("div");c.classList.add("ui-window__titlebar");a.g.appendChild(c);a.i=c;var d=document.createElement("span");d.classList.add("ui-window__title");d.textContent="Particle Palette";c.appendChild(d);
c=document.createElement("div");c.classList.add("ui-window__controls");a.i.appendChild(c);d=document.createElement("button");d.classList.add("ui-window__title-button");var e=document.createElement("img");e.src="./assets/icons/close.svg";d.appendChild(e);c.appendChild(d);a.H=d;d=document.createElement("div");d.classList.add("ui-window__content-area");d.style.flexDirection="column";a.g.appendChild(d);e=document.createElement("div");e.classList.add("ui-window__category-strip","strip-bottom");a.m=e;c=
document.createElement("div");c.classList.add("ui-window__content-container");a.R=c;d.appendChild(c);d.appendChild(e);d=null;b?d=b:(d=document.createElement("div"),d.classList.add("ui-window__content"));d.id="container-0";c.appendChild(d);a.j.push(d);Pa(a,"Solids","./assets/icons/solid.svg",0)}
function Pa(a,b,c,d){const e=document.createElement("button");e.classList.add("ui-window__category-button");const g=document.createElement("img");g.alt=b;g.src=c;e.title=b;g.classList.add("ui-window__category-icon");e.appendChild(g);a.G.push(e);a.m.appendChild(e);e.addEventListener("click",()=>Qa(a,d))}
function Qa(a,b){a.j.forEach((c,d)=>{c.style.display=d===b?"":"none"});a.m.querySelectorAll(".ui-window__category-button").forEach((c,d)=>{d===b?c.classList.add("active"):c.classList.remove("active")})}function X(a,b,c,d){let e=a.j.length,g=null;d?g=d:(g=document.createElement("div"),g.classList.add("ui-window__content"));g.id="container-"+e;g.style.display="none";a.R.appendChild(g);a.j.push(g);Pa(a,b,c,e);a.m.style.display="flex"}
function Ra(a){const b=document.createElement("div");b.classList.add("ui-flex-spacer");a.m.appendChild(b)}
const Ta=class{constructor(a,b){var c={width:250,height:200},d={width:420,height:400};this.j=[];this.G=[];this.v=()=>{Sa++;this.g.style.zIndex=Sa.toString()};this.C=e=>{if(e.stopPropagation(),this.v(),e.button===0){this.i.setPointerCapture(e.pointerId);const g=this.g.getBoundingClientRect();this.o.x=e.clientX-g.left;this.o.y=e.clientY-g.top;this.l=!0}else this.l=!1};this.F=e=>{this.l&&(this.i.releasePointerCapture(e.pointerId),this.l=!1)};this.D=e=>{if(this.l){const g=Math.max(0,Math.min(e.clientY-
this.o.y,window.innerHeight-this.g.offsetHeight));this.g.style.left=`${Math.max(0,Math.min(e.clientX-this.o.x,window.innerWidth-this.g.offsetWidth))}px`;this.g.style.top=`${g}px`}};this.T=()=>{window.removeEventListener("resize",this.L);this.i.removeEventListener("pointerdown",this.C);this.i.removeEventListener("pointermove",this.D);this.i.removeEventListener("pointerup",this.F);this.g.removeEventListener("mousedown",this.v);this.g&&this.g.parentElement&&this.g.parentElement.removeChild(this.g)};
this.L=()=>{const e=Math.max(0,window.innerWidth-this.g.offsetWidth),g=Math.max(0,window.innerHeight-this.g.offsetHeight),f=this.g.offsetLeft,k=this.g.offsetTop;let m=f,l=k;f>e?m=e:f<0&&(m=0);k>g?l=g:k<0&&(l=0);(m!==f||l!==k)&&(this.g.style.left=`${m}px`,this.g.style.top=`${l}px`)};this.V=e=>{e.stopPropagation()};this.S=e=>{document.querySelectorAll(".dropdown-list.is-open").forEach(g=>{const f=g.closest(".custom-dropdown-container");f&&!f.contains(e.target)&&g.classList.remove("is-open")})};this.W=
a;c.width=Math.max(40,Math.min(c.width,d.width));c.height=Math.max(40,Math.min(c.height,d.height));this.M=c;this.K=d;this.l=!1;this.o={x:0,y:0};Oa(this,b);this.g.addEventListener("mousedown",this.v);this.i.addEventListener("pointerdown",this.C);this.i.addEventListener("pointermove",this.D);this.i.addEventListener("pointerup",this.F);this.H.addEventListener("click",this.T);this.H.addEventListener("pointerdown",this.V);window.addEventListener("resize",this.L);this.v();document.addEventListener("click",
this.S)}};var Sa;Sa=100;
function Ua(a){const b=a.i;b.addEventListener("pointerdown",a.V);b.addEventListener("pointermove",a.W);b.addEventListener("pointerup",a.ra);b.addEventListener("pointercancel",a.L);b.addEventListener("lostpointercapture",a.L);b.addEventListener("pointerenter",a.M);b.addEventListener("pointerleave",a.R);b.addEventListener("focus",a.M);b.addEventListener("blur",a.R);b.addEventListener("wheel",a.ya,{passive:!1});a.K.addEventListener("contextmenu",a.ua);window.addEventListener("pointerup",a.S);window.addEventListener("mouseup",
a.S);document.addEventListener("visibilitychange",a.wa)}
function Va(a,b){var c=document.createElement("div");c.classList.add("particle-palette-container");c=new Ta(a.K,c);var d=document.createElement("div");d.classList.add("particle-palette-container");X(c,"Liquids","./assets/icons/liquid.svg",d);d=document.createElement("div");d.classList.add("particle-palette-container");X(c,"Gases","./assets/icons/gas.svg",d);d=document.createElement("div");d.classList.add("particle-palette-container");X(c,"Sands","./assets/icons/sand.svg",d);d=document.createElement("div");
d.classList.add("particle-palette-container");X(c,"Electronics","./assets/icons/electronics.svg",d);Ra(c);X(c,"Settings","./assets/icons/settings.svg");Qa(c,1);a.v=2;const e=c.j;c=c.G;for(let g=0;g<c.length-1;g++)c[g].addEventListener("click",()=>{for(var f of e){const k=f.querySelector(".selected");k&&k.classList.remove("selected")}(f=e[g])&&(f=f.querySelector(".particle-button"))&&(f.classList.add("selected"),a.C=parseInt(f.dataset.Fa||"-1",10),a.v=parseInt(f.dataset.h||"-1",10))});c=!1;for(const g in b){const f=
b[g];if(!f)continue;d=e[f.h-1];if(!d)continue;const k=f.aa,m=f.da,l=la(B(k))>210?"#323238":"#FFFFFFFF",t=B(l),p=document.createElement("button");p.className="particle-button";p.textContent=f.name;p.style.setProperty("--particle-button-base-color",k);p.style.setProperty("--particle-button-variant-color",m);p.style.color=l;p.style.textShadow=`1px 1px 2px rgba(${t[0]}, ${t[1]}, ${t[2]}, 0.6)`;p.dataset.Fa=f.id.toString();p.dataset.h=f.h.toString();p.addEventListener("click",()=>{for(const w of e){const x=
w.querySelector(".selected");x&&x.classList.remove("selected")}p.classList.add("selected");a.C=f.id;a.v=f.h});d.appendChild(p);!c&&f.h===a.v&&(p.classList.add("selected"),a.C=f.id,c=!0)}}
function La(a,b,c){var d=a.l;const e=[],g=a.D,f=a.F,k=[-1,1];a=(t,p)=>{for(const w of k)for(const x of k){const v=b+t*x,y=c+p*w,r=b+p*x,D=c+t*w;v>=0&&v<g&&y>=0&&y<f&&e.push({index:(f-y)*g+v,value:new Uint8ClampedArray([227,227,227,180])});r>=0&&r<g&&D>=0&&D<f&&e.push({index:(f-D)*g+r,value:new Uint8ClampedArray([227,227,227,180])})}};let m=d,l=0;d-=d;for(a(m,l);l<m;)l++,d<0?d+=2*l+1:(m--,d+=2*(l-m)+1),a(m,l);return e}
class Wa{constructor(a,b,c){this.V=d=>{this.m=d.pointerId;d.button===0?(this.g=!0,this.j=!1):d.button===2?(this.j=!0,this.g=!1):(this.g=!1,this.j=!1);try{this.i.setPointerCapture(d.pointerId)}catch{}const e=this.i.getBoundingClientRect(),g=this.F/e.height;this.o.x=this.D/e.width*(d.clientX-e.left);this.o.y=this.i.height-(d.clientY-e.top)*g};this.ra=d=>{if(this.m===d.pointerId){this.m=null;try{this.i.releasePointerCapture(d.pointerId)}catch{}}this.j=this.g=!1};this.W=d=>{var e=this.i.getBoundingClientRect();
const g=this.i.height/e.height;if(this.o.x=this.D/e.width*(d.clientX-e.left),this.o.y=this.i.height-(d.clientY-e.top)*g,typeof d.buttons=="number")e=(d.buttons&2)===2,this.g=(d.buttons&1)===1,this.j=e};this.L=d=>{if(this.g=!1,this.j=!1,this.m===d.pointerId){try{this.i.releasePointerCapture(d.pointerId)}catch{}this.m=null}};this.S=()=>{this.j=this.g=!1;this.m=null};this.wa=()=>{document.hidden&&(this.g=!1,this.j=!1,this.m=null)};this.ya=d=>{d.preventDefault();this.T=!0;this.G=d.deltaY};this.ua=d=>
{d.preventDefault()};this.M=()=>{this.H=!0};this.R=()=>{this.H=!1};this.K=b;this.i=c;this.D=z.J;this.F=z.I;this.sa=z.pa;this.ta=z.oa;this.C=z.Aa;this.v=z.za;this.l=z.na;this.m=null;this.j=this.g=!1;this.H=!0;this.T=!1;this.G=0;this.o={x:0,y:0};Ua(this);Va(this,a)}}var R,Xa,U,Y,V,W,Z,Ma,Na,Ya;
class Za{constructor(a){n(this,Ma);n(this,R);n(this,Xa);n(this,U);n(this,Y);n(this,V);n(this,W);n(this,Z);q(this,R,!1);q(this,Xa,!1);q(this,U,new Map);q(this,Y,0);q(this,V,0);q(this,W,0);q(this,Z,0);u(this,Ma,Ya).call(this,a)}get Da(){return h(this,Xa)}}R=new WeakMap;Xa=new WeakMap;U=new WeakMap;Y=new WeakMap;V=new WeakMap;W=new WeakMap;Z=new WeakMap;Ma=new WeakSet;
Na=function(a,b){const c=a-h(this,Z);c>=1E3&&(q(this,V,h(this,Y)*1E3/c),q(this,W,b.ca*1E3/c),q(this,Y,0),b.ca=0,q(this,Z,a));aa(this,Y).Y++};
Ya=function(a){var b=document.createElement("div");b.classList.add("debug-container");a.appendChild(b);h(this,U).set("debug-container",b);a=document.createElement("div");a.classList.add("debug-info-container");b.appendChild(a);h(this,U).set("info-container",a);b=document.createElement("div");b.classList.add("debug-info");a.appendChild(b);h(this,U).set("fps",b);b=document.createElement("div");b.classList.add("debug-info");a.appendChild(b);h(this,U).set("tps",b)};
(async function(){try{z.J=Math.max(40,Math.min(400,z.J));z.I=Math.max(40,Math.min(400,z.I));z.X=Math.max(4,Math.min(1E3,z.X));Object.freeze(z);const a=document.getElementById("main-canvas");if(!(a instanceof HTMLCanvasElement))throw Error("HTML element 'main-canvas' does not exist.");const b=document.getElementById("main-panel");if(!(b instanceof HTMLDivElement))throw Error("HTML element 'main-panel' does not exist.");a.style.aspectRatio=(z.J/z.I).toString();const c=new ja(a),d=await ea(),e=new Wa(d,
b,a),g=new Za(b);q(g,R,!0);(new Ka(d,c,e,g)).start();console.log(d)}catch(a){console.error("ERROR: Failed to initialize engine due to data loading failure.",a)}})();
