var u=(a,b)=>{if(!b.has(a))throw TypeError("Cannot read from private field");return b.get(a)},w=(a,b)=>{if(b.has(a))throw TypeError("Cannot add the same private member more than once");b instanceof WeakSet?b.add(a):b.set(a,void 0)},x=(a,b,c)=>{if(!b.has(a))throw TypeError("Cannot write to private field");b.set(a,c)},y=(a,b,c)=>{if(!b.has(a))throw TypeError("Cannot access private method");return c};
(function(){function a(c){if(!c.Ba){c.Ba=!0;var d={};d=(c.integrity&&(d.integrity=c.integrity),c.referrerPolicy&&(d.referrerPolicy=c.referrerPolicy),c.crossOrigin==="use-credentials"?d.credentials="include":c.crossOrigin==="anonymous"?d.credentials="omit":d.credentials="same-origin",d);fetch(c.href,d)}}const b=document.createElement("link").relList;if(!(b&&b.supports&&b.supports("modulepreload"))){for(const c of document.querySelectorAll('link[rel="modulepreload"]'))a(c);(new MutationObserver(c=>
{for(const d of c)if(d.type==="childList")for(const f of d.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&a(f)})).observe(document,{childList:!0,subtree:!0})}})();function aa(a,b,c){if(a.u.push(...b),c){const d=a.g.A,f=a.g.v;for(const e of b)a.m.push({index:(f-1-e.position.y)*d+e.position.x,value:c})}}
function ba(a,b,c){var d=a.g.O;const f=[],e=a.g.A,l=a.g.v,h=[-1,1];a=(m,n)=>{for(const r of h)for(const p of h){const q=b+m*p,t=c+n*r,v=b+n*p,D=c+m*r;q>=0&&q<e&&t>=0&&t<l&&f.push({index:(l-t)*e+q,value:new Uint8ClampedArray([227,227,227,180])});v>=0&&v<e&&D>=0&&D<l&&f.push({index:(l-D)*e+v,value:new Uint8ClampedArray([227,227,227,180])})}};let k=d,g=0;d-=d;for(a(k,g);g<k;)g++,d<0?d+=2*g+1:(k--,d+=2*(g-k)+1),a(k,g);return f}
function z(a,b){for(const {index:d,value:f}of b){var c=f[3];b=c/255;const e=Math.round(f[1]*b+a[d*4+1]*(1-b)),l=Math.round(f[2]*b+a[d*4+2]*(1-b));c=Math.min(a[d*4+3],c);a[d*4]=Math.round(f[0]*b+a[d*4]*(1-b));a[d*4+1]=e;a[d*4+2]=l;a[d*4+3]=c}}
class ca{constructor(a,b){this.g=a;this.h=b;this.l=this.h.getContext("2d");this.i=new Uint8ClampedArray(this.g.A*this.g.v*4);this.u=[];this.m=[];this.B=[];this.h.style.aspectRatio=(this.g.A/this.g.v).toString();this.h.width=this.g.A;this.h.height=this.g.v;this.l.imageSmoothingEnabled=!1;this.l.translate(0,this.h.height);this.l.scale(1,-1)}}
const A=Object.freeze({Ua:new Uint8ClampedArray([255,255,255,255]),ha:new Uint8ClampedArray([0,0,0,255]),Ma:new Uint8ClampedArray([128,128,128,255]),RED:new Uint8ClampedArray([255,0,0,255]),Na:new Uint8ClampedArray([0,255,0,255]),Ha:new Uint8ClampedArray([0,0,255,255]),Va:new Uint8ClampedArray([255,255,0,255]),Ia:new Uint8ClampedArray([0,255,255,255]),Oa:new Uint8ClampedArray([255,0,255,255]),Ra:new Uint8ClampedArray([0,0,0,0]),Qa:new Uint8ClampedArray([255,255,255,128])});
function da(a){if(a==null)return A.ha;a=a.replace("#","");if(a.length===6)a+="FF";else if(a.length===3){let c="";for(var b of a)c+=b,c+=b;a=c+"FF"}else return A.ha;b=parseInt(a,16);return new Uint8ClampedArray([b>>24&255,b>>16&255,b>>8&255,b&255])}function ea(a){a=a.startsWith("#")?a.substring(1):a;if(a.length<6)return 0;a=parseInt(a,16);return.299*(a>>16&255)+.587*(a>>8&255)+.114*(a&255)}
function fa(a){a=[...a];for(let b=a.length-1;b>0;b--){const c=Math.floor(Math.random()*(b+1));[a[b],a[c]]=[a[c],a[b]]}return a}function ha(a){var b=Math.max(10,Math.min(a,80));const c=b*Math.PI/180;a=[];(a.push([{dx:0,dy:-1}]),b<50)?(a.push([{dx:1,dy:-1},{dx:-1,dy:-1}]),b=Math.round(1/Math.tan(c)),a.push([{dx:b,dy:-1},{dx:b*-1,dy:-1}])):(b=Math.round(Math.tan(c)),a.push([{dx:1,dy:-b},{dx:-1,dy:-b}]));return a}
const ia=Object.freeze({qa:[{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1},{dx:-1,dy:0},{dx:1,dy:0},{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1}]}),B=Object.freeze({Sa:{dx:-1,dy:1},za:{dx:0,dy:1},Ta:{dx:1,dy:1},ya:{dx:-1,dy:0},Pa:{dx:1,dy:0},Ka:{dx:-1,dy:-1},Ja:{dx:0,dy:-1},La:{dx:1,dy:-1}});var C,E,F,G,ja;function H(a,b){u(a,E).add(b.index);b=ka(a,b);for(const c of b)u(a,E).add(c.index)}
function I(a,b,c,d=!1){for(var f of c)if(f){c=fa(f);for(const e of c)if(c=e.dx,d&&Math.random()>.5&&(c=e.dx*-1),(c=a.P(b.position.x+c,b.position.y+e.dy))&&c.S&&b.D>c.D)return u(a,C)[c.index]=b,u(a,C)[b.index]=c,d={x:b.position.x,y:b.position.y},f=b.index,b.position=c.position,b.index=c.index,c.position=d,c.index=f,H(a,b),H(a,c),c}return null}
function la(a,b,c){u(a,C)[b.index]=c;u(a,C)[c.index]=b;const d={x:b.position.x,y:b.position.y},f=b.index;b.position=c.position;b.index=c.index;c.position=d;c.index=f;H(a,b);H(a,c)}function J(a,b,c){return a.P(b.position.x+c.dx,b.position.y+c.dy)}function ka(a,b){return ia.qa.map(c=>J(a,b,c)).filter(c=>c!==null).filter(()=>!0)}
function ma(a,b,c,d,f){for(let g=-d;g<=d;g++)for(let m=-d;m<=d;m++)if(!(g*g+m*m>d*d)){var e=b+g,l=c+m;if(e>=0&&e<a.width&&l>=0&&l<a.height){var h=a.P(e,l);if(f===0||h===null||h.id===0){h=a;var k=f;e>=0&&e<h.width&&l>=0&&l<h.height&&(k=y(h,F,G).call(h,k),k.position.x=e,k.position.y=l,k.index=l*h.width+e,H(h,k),u(h,C)[l*h.width+e]=k)}}}}
class na{constructor(a,b,c){w(this,F);w(this,C);w(this,E);this.width=a;this.height=b;x(this,C,Array(a*b));x(this,E,new Set);this.Z=c;y(this,F,ja).call(this,0)}get data(){return u(this,C)}get g(){return u(this,E)}P(a,b){return a>=0&&a<this.width&&b>=0&&b<this.height?u(this,C)[b*this.width+a]:null}}C=new WeakMap;E=new WeakMap;F=new WeakSet;
G=function(a){a=this.Z[a];if(!a)return null;var b=Math.round(Math.random()*5)/5;const c=da(a.X),d=da(a.fa);b=new Uint8ClampedArray([c[0]+(d[0]-c[0])*b,c[1]+(d[1]-c[1])*b,c[2]+(d[2]-c[2])*b,c[3]+(d[3]-c[3])*b]);b={handle:-1,id:a.id,name:a.name,color:b,position:{x:-1,y:-1},index:0,S:a.S,D:a.D};return a.j===0?{...b,j:0}:a.j===1?{...b,j:1}:a.j===2?{...b,j:2,Wa:0,ma:a.ma}:a.j===3?{...b,j:3}:a.j===4?{...b,j:4,na:a.na,da:a.da}:a.j===5?{...b,j:5,node:-1}:null};
ja=function(a){const b=this.width,c=this.height;x(this,C,Array(b*c));for(let d=0;d<c;d++)for(let f=0;f<b;f++){let e=d*b+f,l=y(this,F,G).call(this,a);l&&(l.position.x=f,l.position.y=d,l.index=e,u(this,C)[e]=l,u(this,E).add(l.index))}};var K,oa;
function pa(a){var b=[];for(const c of a.o.g)b.push(a.o.data[c]);a.l++;a.l>2&&(a.o.g.clear(),a.l=0);aa(a.N,b,a.B.Ca?new Uint8ClampedArray([210,55,55,180]):void 0);a.C.clear();b=fa(b);b.sort((c,d)=>c.position.y-d.position.y);for(const c of b)if(c&&!a.C.has(c.index))switch(c.j){case 2:qa(a,c);break;case 3:ra(a,c);break;case 4:y(a,K,oa).call(a,c)}b=sa(a.o);ta(a,b)}
function qa(a,b){const c=I(a.o,b,[[{dx:0,dy:-1}],[{dx:-1,dy:-1},{dx:1,dy:-1}],[{dx:-1,dy:0},{dx:1,dy:0}]],!1);c&&(a.C.add(b.index),a.C.add(c.index))}function ra(a,b){const c=I(a.o,b,[[B[a.M[Math.floor(Math.random()*a.M.length)]]]],!1);c&&(a.C.add(b.index),a.C.add(c.index))}
function sa(a){const b=a.width;var c=a.height;const d=[],f=[],e={};for(--c;c>=0;c--)for(let m=0;m<b;m++){var l=c*b+m,h=a.P(m,c);if(!h||h.j!==2||h.j!==2)continue;const n=J(a,h,B.za);var k=J(a,h,B.ya),g=n&&n.id===h.id;const r=k&&k.id===h.id;let p=-1;r&&(p=c*b+(m-1));let q=-1;g&&(q=(c+1)*b+m);k=n&&n.id===0;if(r||g)if(r&&!g)g=e[p],d[g].push(l),k&&(f[g].H.push(h),f[g].I.push(n)),e[l]=g;else if(!r&&g)g=e[q],d[g].push(l),k&&(f[g].H.push(h),f[g].I.push(n)),e[l]=g;else{if(g=e[q],d[g].push(l),k&&(f[g].H.push(h),
f[g].I.push(n)),e[l]=g,l=e[p],l!==g){h=f[l];for(const t of h.H)f[g].H.push(t);for(const t of h.I)f[g].I.push(t);h=d[l];for(const t of h)e[t]=g;d[l]=[];f[l]={H:[],I:[]}}}else g=f.length,d.push([l]),f.push({H:[],I:[]}),k&&(f[g].H.push(h),f[g].I.push(n)),e[l]=g}return f.filter(m=>m.H.length>30)}
function ta(a,b){for(const c of b){b=c.H.sort((h,k)=>k.position.y-h.position.y);const d=c.I.sort((h,k)=>h.position.y-k.position.y),f=b.length;let e=0;const l=f/4;for(let h=0;h<f;h++){const k=b[h],g=d[h];if(Math.sqrt(k.position.x*g.position.x+k.position.y*g.position.y),k.position.y>g.position.y&&(la(a.o,k,g),a.C.add(k.index),a.C.add(g.index),e++,e>=l))break}}}
class ua{constructor(a,b,c){w(this,K);this.m=!1;this.l=this.h=this.u=this.i=0;this.M=Object.keys(B);this.J=d=>{if(this.m){this.i===0&&(this.i=d);var f=d-this.i;this.i=d;var e=this.B;if(e.i){if(e.frameCount++,d>=e.g+1E3){var l=d-e.g;e.l=e.frameCount*1E3/l;e.m=this.u*1E3/l;this.u=e.frameCount=0;e.g=d}e.ca&&(e.ca.textContent=`FPS: ${e.l.toFixed(0)}`);e.ea&&(e.ea.textContent=`TPS: ${e.m.toFixed(0)}`)}this.g.K||(this.g.G?ma(this.o,Math.floor(this.g.T),Math.floor(this.g.U),this.g.O,0):this.g.F&&ma(this.o,
Math.floor(this.g.T),Math.floor(this.g.U),this.g.O,this.g.W));this.h+=f;for(d=0;this.h>=this.L;)if(pa(this),d++,this.u++,this.h-=this.L,d>60){this.h=0;break}d=this.N;d.g.R&&(d.B=ba(d,Math.floor(d.g.T),Math.floor(d.g.U)));l=d.u;f=d.g.A;e=d.g.v;for(var h of l){l=(e-1-h.position.y)*f+h.position.x;let k=h.color;d.i[l*4]=k[0];d.i[l*4+1]=k[1];d.i[l*4+2]=k[2];d.i[l*4+3]=k[3]}h=new Uint8ClampedArray(d.i);z(h,d.m);z(h,d.B);h=new ImageData(h,d.g.A,d.g.v);d.l.putImageData(h,0,0);d.u.length=0;d.m=[];d.B=[];requestAnimationFrame(this.J)}};
this.g=a;this.N=b;this.B=c;this.o=new na(this.g.A,this.g.v,this.g.Z);this.C=new Set;this.$=this.g.$;this.L=this.g.L;this.g.o=this.o}start(){this.m||(this.m=!0,this.i=0,requestAnimationFrame(this.J))}}K=new WeakSet;oa=function(a){const b=I(this.o,a,a.da,!0);b&&(this.C.add(a.index),this.C.add(b.index))};
function va(a,b,c,d){var f=L;const e=document.createElement("div");return e.classList.add("ui-window"),e.style.left=`${b.x}px`,e.style.top=`${b.y}px`,e.style.width=`${c.width}px`,e.style.height=`${c.height}px`,e.style.maxWidth=`${d.width}px`,e.style.maxHeight=`${d.height}px`,e.style.zIndex=f.toString(),e.addEventListener("mousedown",a.ga),e}
function wa(a,b){const c=document.createElement("div");c.classList.add("ui-window__title-bar");const d=document.createElement("span");return d.classList.add("ui-window__title"),d.textContent=b,c.appendChild(d),c.addEventListener("pointerdown",a.sa),c.addEventListener("pointermove",a.va),c.addEventListener("pointerup",a.wa),c}
function xa(a){const b=document.createElement("div");b.classList.add("ui-window__title-bar__button__wrapper");const c=document.createElement("button");c.classList.add("ui-window__title-bar__button");const d=document.createElement("img");return d.src="./assets/icons/close.svg",c.appendChild(d),b.appendChild(c),c.addEventListener("pointerdown",f=>{f.stopPropagation()}),c.addEventListener("click",()=>{M(a,!1)}),b}
function ya(){const a=document.createElement("div");return a.classList.add("ui-window__content__wrapper","left"),a}function za(){const a=document.createElement("div");return a.classList.add("ui-window__content-bar"),a}function Aa(){const a=document.createElement("div");return a.classList.add("ui-window__content-container"),a}function M(a,b){b?a.g.classList.add("is-visible"):a.g.classList.remove("is-visible");a.isVisible=b}
function Ba(a,b){a.l.classList.remove("top","bottom","left","right");a.l.classList.add(b)}function Ca(a,b){(b=a.h[b])&&Da(a,b)}
function N(a,b,c,d){let f=a.h.length;a.h.length!==0&&(b.style.display="none");b.id="container-"+f;a.N.appendChild(b);const e=document.createElement("button");e.classList.add("ui-window__content-bar__button");e.title=c;a.u.appendChild(e);const l=document.createElement("img");l.classList.add("ui-window__content-bar__button__icon");l.alt=c;l.src=d;e.appendChild(l);e.addEventListener("click",()=>Ca(a,f));a.M.push(e);a.h.push(b)}
function Da(a,b){const c=a.h;for(let d=0;d<c.length;d++){const f=c[d];if(f===b){a.h.forEach(e=>{e.style.display="none"});f.style.display="";a.M.forEach((e,l)=>{l===d?e.classList.add("active"):e.classList.remove("active")});break}}}function Ea(a){const b=document.createElement("div");b.classList.add("ui-window__content-bar__separator");b.classList.add("is-spacer");a.u.appendChild(b)}
const O=class{constructor(a,b,c,d,f){this.h=[];this.M=[];this.m=!1;this.B={x:0,y:0};this.xa=()=>{const e=this.g.offsetLeft,l=this.g.offsetTop,h=Math.max(0,Math.min(e,Math.max(0,this.i.offsetWidth-this.g.offsetWidth))),k=Math.max(0,Math.min(l,Math.max(0,this.i.offsetHeight-this.g.offsetHeight)));(h!==e||k!==l)&&(this.g.style.left=`${h}px`,this.g.style.top=`${k}px`)};this.ga=()=>{L++;this.g.style.zIndex=L.toString()};this.sa=e=>{if(e.stopPropagation(),this.ga(),e.button===0){this.J.setPointerCapture(e.pointerId);
const l=this.g.getBoundingClientRect();this.B.x=e.clientX-l.left;this.B.y=e.clientY-l.top;this.m=!0}else this.m=!1};this.wa=e=>{this.m&&(this.J.releasePointerCapture(e.pointerId),this.m=!1)};this.va=e=>{if(this.m){const l=this.i.getBoundingClientRect(),h=Math.max(0,Math.min(e.clientY-this.B.y-l.top,this.i.offsetHeight-this.g.offsetHeight));this.g.style.left=`${Math.max(0,Math.min(e.clientX-this.B.x-l.left,this.i.offsetWidth-this.g.offsetWidth))}px`;this.g.style.top=`${h}px`}};this.title=b;this.position=
c;this.size=d;this.isVisible=!1;this.i=a;this.g=va(this,c,d,f);this.J=wa(this,b);this.ra=xa(this);this.l=ya();this.u=za();this.N=Aa();this.i.appendChild(this.g);this.J.appendChild(this.ra);this.g.appendChild(this.J);this.l.appendChild(this.u);this.l.appendChild(this.N);this.g.appendChild(this.l);window.addEventListener("resize",this.xa)}};var L=100;function P(a,b=1){const c=document.createElement("div");c.classList.add("ui-window__content__separator");c.style.height=`${b}px`;a.g.appendChild(c)}
function Fa(a,b){const c=document.createElement("h3");c.classList.add("ui-window__content__heading-title");c.textContent=b;a.g.appendChild(c)}function Q(a,b){const c=document.createElement("h4");c.classList.add("ui-window__content__heading-section");c.textContent=b;a.g.appendChild(c)}
function R(a,b,c){const d=document.createElement("div");d.classList.add("ui-window__helper__flex-row","ui-window__content__info-row");const f=document.createElement("label");f.textContent=`${b}:`;d.appendChild(f);b=document.createElement("div");b.classList.add("ui-window__helper__spacer");d.appendChild(b);b=document.createElement("span");return b.classList.add("ui-window__content__info-value"),b.textContent=c,d.appendChild(b),(c.length===0?!1:/^#([0-9A-Fa-f]{3,4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$/.test(c.trim()))&&
(b.style.backgroundColor=c,b.style.padding="0 6px",b.style.borderRadius="6px",b.style.color=ea(c)>115?"#323238":"#FFFFFF"),a.g.appendChild(d),d}
function Ga(a){const b=document.createElement("div");b.classList.add("ui-window__helper__flex-row");var c=document.createElement("label");c.textContent="Select Particle:";b.appendChild(c);c=document.createElement("div");c.classList.add("ui-window__helper__spacer");b.appendChild(c);c=document.createElement("button");c.classList.add("ui-window__mini-button");c.style.backgroundColor="transparent";const d=document.createElement("img");return d.classList.add("ui-window__mini-button__icon"),d.src="./assets/icons/dropper.svg",
c.appendChild(d),b.appendChild(c),a.g.appendChild(b),b}
function S(a,b,c,d,f,e){const l=document.createElement("div");l.classList.add("ui-window__helper__flex-row");const h=document.createElement("label");h.textContent=b+":";l.appendChild(h);const k=document.createElement("input");k.type="range";k.min=c.toString();k.max=d.toString();k.value=f.toString();k.step=e.toString();l.appendChild(k);const g=document.createElement("input");g.style.minWidth="40px";g.type="number";g.min=c.toString();g.max=d.toString();g.value=f.toString();g.step=e.toString();l.appendChild(g);
k.oninput=()=>g.value=k.value;g.onchange=()=>{const m=Math.max(c,Math.min(d,parseInt(g.value))).toString();k.value=m;g.value=m};a.g.appendChild(l)}function T(a,b,c,d){const f=document.createElement("button");f.classList.add("ui-window__content__button");f.textContent=b;c!=null&&(f.id=c);d!=null&&(f.style.backgroundColor=d);a.g.appendChild(f)}
function U(a,b,c,d=0,f){const e=document.createElement("div");e.classList.add("ui-window__helper__flex-row");const l=document.createElement("label");l.textContent=b+":";e.appendChild(l);const h=document.createElement("div");h.classList.add("ui-window__content__dropdown-button__wrapper");e.appendChild(h);const k=document.createElement("div");k.classList.add("ui-window__content__dropdown-button");const g=document.createElement("span");g.textContent=c[0]?c[0]:"Template Item";f!=null&&(g.id=`${f}-display`);
k.appendChild(g);h.appendChild(k);const m=document.createElement("ul");m.classList.add("ui-window__content__dropdown-list");f!=null&&(m.id=`${f}-list`);h.appendChild(m);let n=Math.max(0,Math.min(d,c.length-1));const r=[];for(let p=0;p<c.length;p++){const q=c[p],t=document.createElement("li");t.style.marginBottom="0px";t.classList.add("ui-window__content__dropdown-item");t.textContent=q;t.dataset.index=p.toString();t.dataset.value=q.toLowerCase().replace(/\s/g,"-");p===n&&(t.classList.add("is-selected"),
g.textContent=q);t.addEventListener("click",v=>{v.stopPropagation();r[n].classList.remove("is-selected");n=p;t.classList.add("is-selected");g.textContent=q;m.classList.remove("is-open")});m.appendChild(t);r.push(t)}return k.addEventListener("click",p=>{if(p.stopPropagation(),m.classList.toggle("is-open")){m.parentElement;m.dataset.Fa=h.id;document.body.appendChild(m);var q=k.getBoundingClientRect();p=m.getBoundingClientRect();p=m.scrollHeight||p.height;const v=document.documentElement.clientHeight;
m.style.position="absolute";m.style.left=`${q.left}px`;m.style.width=`${q.width}px`;m.style.zIndex="9999";var t=m.querySelector(".dropdown-item.is-selected");t?(t=t.offsetTop,q=q.top-t,q<0&&(q=0),q+p>v&&(q=Math.max(0,v-p)),m.style.top=`${Math.round(q)}px`,m.scrollTop=t):(q=q.bottom,q+p>v&&(q=Math.max(0,v-p)),m.style.top=`${Math.round(q)}px`,m.scrollTop=0)}else m.parentElement===document.body&&h.appendChild(m)}),a.g.appendChild(e),{button:k,items:r}}
function V(a,b){const c=document.createElement("div");c.classList.add("ui-window__helper__flex-row");const d=document.createElement("label");d.textContent=b+":";c.appendChild(d);b=document.createElement("div");b.classList.add("ui-window__content__toggle-button__wrapper");c.appendChild(b);const f=document.createElement("div");f.classList.add("ui-window__content__toggle-button");f.dataset.state="off";b.appendChild(f);b=document.createElement("span");b.classList.add("ui-window__content__toggle-button__indicator",
"indicator-o");b.textContent="O";f.appendChild(b);b=document.createElement("span");b.classList.add("ui-window__content__toggle-button__indicator","indicator-i");b.textContent="I";f.appendChild(b);b=document.createElement("div");b.classList.add("ui-window__content__toggle-button__slider");f.appendChild(b);f.addEventListener("click",()=>{const e=f.classList.toggle("is-on");f.dataset.state=e?"on":"off"});a.g.appendChild(c)}
class W{constructor(){this.g=document.createElement("div");this.g.classList.add("ui-window__content")}}var X,Y=X||{};X=(Y[Y.ia=1]="Palette",Y[Y.ua=2]="DebugStats",Y[Y.ta=3]="DebugQuickLook",Y);function Ha(){document.addEventListener("click",a=>{document.querySelectorAll(".ui-window__content__dropdown-list.is-open").forEach(b=>{var c=b.dataset.Fa;c=c?document.getElementById(c):null;b.contains(a.target)||c?.contains(a.target)||(b.classList.remove("is-open"),c?.appendChild(b))})})}
function Z(a,b){a:{var c=a.l.get(b);if(!c){switch(b){case 1:c=Ia(a);break;case 2:c=new O(a.i,"Debug Stats",{x:80,y:80},{width:260,height:46},{width:260,height:46});var d=document.createElement("div");d.classList.add("debug__stats-content");N(c,d,"Stats Content","./assets/icons/settings.svg");const f=document.createElement("div");f.classList.add("debug__stats-content__info-container");d.appendChild(f);const e=document.createElement("div");e.classList.add("debug__stats-content__info-container");d.appendChild(e);
if(d=a.g.ka)d.ca=f,d.ea=e;break;case 3:c=Ja(a);break;default:a=void 0;break a}a.l.set(b,c)}a=c}a&&!a.isVisible&&M(a,!0)}
function Ia(a){var b=(h,k,g)=>{k.addEventListener("click",()=>{if(a.g.V!==g+1){a.h&&a.h.classList.remove("selected");var m=h.querySelector(".particle-button");m?(m.classList.add("selected"),a.h=m,a.g.W=parseInt(m.dataset.Ga||"0",10),a.g.V=parseInt(m.dataset.j||"0",10)):(a.g.W=0,a.g.V=0)}})};const c=h=>{const k=document.createElement("button");k.className="particle-button";k.textContent=h.name;var g=ea(h.X)>210;const m=g?"#323238":"#FFFFFF";g=g?"#FFFFFF":"#323238";return k.style.setProperty("--particle-button-base-color",
h.X),k.style.setProperty("--particle-button-variant-color",h.fa),k.style.color=m,k.style.textShadow=`1px 1px 2px rgba(${g[0]}, ${g[1]}, ${g[2]}, 0.6)`,k.dataset.Ga=h.id.toString(),k.dataset.j=h.j.toString(),k},d=new O(a.i,"Particle Palette",{x:390,y:124},{width:332,height:206},{width:420,height:400}),f=(h=>{const k=[];var g=document.createElement("div");g.classList.add("particle-palette-container");N(h,g,"Solids","./assets/icons/solid.svg");k.push(g);g=document.createElement("div");g.classList.add("particle-palette-container");
N(h,g,"Liquids","./assets/icons/liquid.svg");k.push(g);g=document.createElement("div");g.classList.add("particle-palette-container");N(h,g,"Gases","./assets/icons/gas.svg");k.push(g);g=document.createElement("div");g.classList.add("particle-palette-container");N(h,g,"Sands","./assets/icons/sand.svg");k.push(g);g=document.createElement("div");g.classList.add("particle-palette-container");N(h,g,"Electronics","./assets/icons/electronics.svg");k.push(g);g=new W;let {items:m}=U(g,"Orientation",["Top",
"Left","Right","Bottom"],3,"palette-orientation");return m.forEach(n=>{n.addEventListener("click",()=>{const r=n.dataset.value;r&&Ba(h,r)})}),Ea(h),N(h,g.g,"Settings","./assets/icons/settings.svg"),k.push(g.g),k})(d);for(var e=0;e<f.length-1;e++){var l=f[e];const h=d.M[e];h!==void 0&&b(l,h,e)}d.u.classList.add("is-visible");Ba(d,"bottom");Ca(d,1);b=a.g.Z;e=null;for(const h in b){const k=b[h];l=f[k.j-1];if(!l)continue;const g=c(k);g.addEventListener("click",()=>{a.h&&a.h.classList.remove("selected");
g.classList.add("selected");a.h=g;a.g.W=k.id;a.g.V=k.j});l.appendChild(g);!e&&k.j===2&&(e=g,e.classList.add("selected"),a.h=e,a.g.W=k.id,a.g.V=k.j)}return d}
function Ja(a){const b=new O(a.i,"Quick Look",{x:160,y:120},{width:340,height:460},{width:420,height:600}),c=new W;N(b,c.g,"Look up","./assets/icons/settings.svg");const d=Ga(c);P(c,0);Q(c,"Properties:");let f=R(c,"Name","Undefined"),e=R(c,"Color","#000000"),l=R(c,"Position","NaN"),h=R(c,"Index","NaN"),k=R(c,"Handle","NaN"),g=R(c,"Particle ID","NaN"),m=R(c,"Is Movable","NaN"),n=R(c,"Density","NaN");return d.querySelector("button")?.addEventListener("click",()=>{a.g.K?a.g.K=!1:(a.g.Y?.classList.add("cursor-picker"),
a.g.K=!0)}),a.g.Y?.addEventListener("pointerdown",()=>{if(a.g.K){a.g.Y?.classList.remove("cursor-picker");a.g.K=!1;var r=a.g.T,p=a.g.U;if(r=a.g.o?.P(Math.floor(r),Math.floor(p))){(p=k.querySelector("span"))&&(p.textContent=r.handle.toString());(p=g.querySelector("span"))&&(p.textContent=r.id.toString());(p=f.querySelector("span"))&&(p.textContent=r.name);let q=e.querySelector("span");if(q){const [t,v,D,Ma]=r.color;p=`#${t.toString(16).padStart(2,"0")}${v.toString(16).padStart(2,"0")}${D.toString(16).padStart(2,
"0")}${Ma.toString(16).padStart(2,"0")}`;q.textContent=p;q.style.backgroundColor=p}(p=l.querySelector("span"))&&(p.textContent=`X: ${r.position.x},Y: ${r.position.y}`);(p=h.querySelector("span"))&&(p.textContent=r.index.toString());(p=m.querySelector("span"))&&(p.textContent=r.S.toString());(p=n.querySelector("span"))&&(p.textContent=r.D.toString())}}}),b}class Ka{constructor(a,b){this.l=new Map;this.h=null;this.i=a;this.g=b;Ha()}}
function La(a){const b=[{id:"bog-menu-item",items:["Settings","Quit"]},{id:"world-item",items:["Particle Palette"]},{id:"debug-item",items:["Quick Look","Stats","Debug Menu"]},{id:"help-item",items:["About","Report Issue"]}],c=[];for(let f=0;f<b.length;f++){var d=b[f];if(!d)continue;const e=document.getElementById(d.id);if(!(e instanceof HTMLDivElement))continue;d=Na(e,d.items);d.items.forEach(h=>{c.push(h)});const l=d.Ea;e.addEventListener("click",h=>{h.stopPropagation();(h=document.querySelector(".app-menu__dropdown.is-open"))&&
h!==l&&h.classList.remove("is-open");a.m=l.classList.toggle("is-open")});e.addEventListener("mouseenter",()=>{if(a.m&&!l.classList.contains("is-open")){const h=document.querySelector(".app-menu__dropdown.is-open");h&&h!==l&&h.classList.remove("is-open");l.classList.add("is-open")}})}c.forEach(f=>{switch(f.textContent){case "Particle Palette":f.classList.remove("is-disabled");f.addEventListener("click",()=>{Z(a.l,X.ia)});break;case "Stats":f.classList.remove("is-disabled");f.addEventListener("click",
()=>{Z(a.l,X.ua)});break;case "Quick Look":f.classList.remove("is-disabled");f.addEventListener("click",()=>{Z(a.l,X.ta)});break;case "About":f.classList.remove("is-disabled");f.addEventListener("click",()=>{window.open("https://github.com/misuldansin/bog-engine/","_blank")});break;case "Report Issue":f.classList.remove("is-disabled"),f.addEventListener("click",()=>{window.open("https://github.com/misuldansin/bog-engine/issues/new","_blank")})}})}
function Oa(a){const b=c=>{const d=a.h.getBoundingClientRect(),f=a.h.height-a.g.v/d.height*(c.clientY-d.top);a.g.T=a.g.A/d.width*(c.clientX-d.left);a.g.U=f};a.h.addEventListener("pointerdown",c=>{switch(b(c),c.button){case 0:a.g.F=!0;break;case 2:a.g.G=!0;break;default:a.g.F=!1,a.g.G=!1}try{a.h.setPointerCapture(c.pointerId)}catch{}a.i=c.pointerId});a.h.addEventListener("pointermove",c=>{b(c);typeof c.buttons=="number"&&(a.g.F=(c.buttons&1)===1,a.g.G=(c.buttons&2)===2)});a.h.addEventListener("pointerup",
c=>{if(a.i===c.pointerId){try{a.h.releasePointerCapture(c.pointerId)}catch{}a.i=null}a.g.F=!1;a.g.G=!1});a.h.addEventListener("pointercancel",c=>{if(a.i===c.pointerId){try{a.h.releasePointerCapture(c.pointerId)}catch{}a.i=null}a.g.F=!1;a.g.G=!1});a.h.addEventListener("lostpointercapture",c=>{if(a.i===c.pointerId){try{a.h.releasePointerCapture(c.pointerId)}catch{}a.i=null}a.g.F=!1;a.g.G=!1});a.h.addEventListener("pointerenter",c=>{b(c);a.g.R=!0});a.h.addEventListener("pointerleave",()=>{a.g.R=!1});
a.h.addEventListener("focus",()=>{a.g.R=!0});a.h.addEventListener("blur",()=>{a.g.R=!1});a.h.addEventListener("wheel",c=>{c.preventDefault();a.g.O=Math.max(0,Math.min(Math.floor(a.g.O-c.deltaY*a.g.ba),a.g.aa))},{passive:!1});window.addEventListener("pointerup",()=>{a.g.F=!1;a.g.G=!1;a.i=null});document.addEventListener("visibilitychange",()=>{document.hidden&&(a.g.F=!1,a.g.G=!1,a.i=null)})}
function Na(a,b){const c=document.createElement("div");c.classList.add("app-menu__dropdown");let d=[];return b.forEach(f=>{const e=document.createElement("div");e.classList.add("app-menu__dropdown-item","is-disabled");e.textContent=f;c.appendChild(e);d.push(e)}),a.appendChild(c),{Ea:c,items:d}}
class Pa{constructor(a,b,c){this.i=null;this.m=!1;this.g=a;this.l=new Ka(b,a);this.u=b;this.h=c;La(this);Oa(this);this.u.addEventListener("contextmenu",d=>{d.preventDefault()});document.addEventListener("click",()=>{const d=document.querySelector(".app-menu__dropdown.is-open");d instanceof HTMLDivElement&&(d.classList.remove("is-open"),this.m=!1)});Z(this.l,X.ia)}}
class Qa{constructor(a){this.ea=this.ca=null;this.g=this.m=this.l=this.frameCount=0;this.Ca=this.i=!1;this.h=new Map;const b=document.createElement("div");b.classList.add("debug-container");a.appendChild(b);this.h.set("debug-container",b);a=document.createElement("div");a.classList.add("debug-info-container");b.appendChild(a);this.h.set("info-container",a)}}
async function Ra(a){try{const b=await fetch(a);if(!b.ok)throw Error(`HTTP error! Status: ${b.status}`);return await b.text()}catch(b){throw console.error(`Failed to read particle data from ${a}:`,b),Error("Failed to load particle data.");}}
async function Sa(){var a=await Ra("./src/data/particles.data");let b={};var c=new Set,d=null;for(var f of a.split("\n"))if(a=f.trim(),a.length!==0&&!a.startsWith("#"))if(a.startsWith("[")&&a.endsWith("]"))a=parseInt(a.slice(1,-1),10),isNaN(a)||a<10?d=null:c.has(a)?(console.warn(`[Loader] Duplicate ID found: ${a}. Ignoring.`),d=null):(c.add(a),d=a,b[a]={});else if(d!==null&&(a=a.split(":").map(e=>e.trim()),a.length===2)){const e=a[1],l=b[d];switch(a[0]){case "name":l.name=e;break;case "category":l.j=
parseInt(e,10);break;case "base_color":l.ja=e;break;case "variant_color":l.pa=e;break;case "is_movable":l.la=e==="true";break;case "density":l.D=parseFloat(e);break;case "max_concentration":l.Da=parseInt(e);break;case "repose_angle":l.oa=parseFloat(e)}}c={};for(const e in b)d=b[e],f=parseInt(e,10),d.name===void 0||d.j===void 0||d.ja===void 0||d.pa===void 0||d.la===void 0||d.D===void 0?console.warn(`[Loader] Corrupted particle block found of ID: ${f}. Missing core properties.`):(a={id:f,name:d.name,
X:d.ja,fa:d.pa,S:d.la,D:d.D},d.j===1?c[f]={...a,j:1}:d.j===2?c[f]={...a,ma:d.Da,j:2}:d.j===3?c[f]={...a,j:3}:d.j===4?c[f]={...a,j:4,na:d.oa,da:ha(d.oa)}:d.j===5&&(c[f]={...a,j:5}));return c[0]={id:0,name:"Empty",j:0,X:"#0E0E11",fa:"#0E0E11",S:!0,D:0},c}
async function Ta(){var a,b,c,d,f,e,l,h,k,g=(await Ra("./src/data/settings.data")).split(/\r?\n/);for(const r of g){var m=r.trim();if(m.length===0||m.startsWith("#"))continue;var n=m.indexOf(".");const p=m.indexOf(":");if(!(p===-1||n===-1||n>=p)&&(g=m.substring(0,n).trim(),n=m.substring(n+1,p).trim(),m=m.substring(p+1).trim(),g&&n&&m!==void 0&&m.length!==0))if(g==="engine")switch(n){case "width":g=parseInt(m);isNaN(g)||(a=g);break;case "height":g=parseInt(m);isNaN(g)||(b=g);break;case "render_interval":g=
parseFloat(m);isNaN(g)||(c=g);break;case "physics_interval":g=parseFloat(m),isNaN(g)||(d=g)}else if(g==="input")switch(n){case "brush_size":g=parseInt(m);isNaN(g)||(f=g);break;case "brush_max_size":g=parseInt(m);isNaN(g)||(e=g);break;case "brush_sensitivity":g=parseFloat(m),isNaN(g)||(l=g)}else if(g==="debug")switch(n){case "start_enabled":m.toLowerCase()==="true"?h=!0:m.toLowerCase()==="false"&&(h=!1);break;case "overlay_start_enabled":m.toLowerCase()==="true"?k=!0:m.toLowerCase()==="false"&&(k=
!1)}}return{A:a??342,v:b??192,$:c??16.667,L:d??25,Aa:f??4,aa:e??42,ba:l??.02,Xa:h??!1,Ya:k??!1}}class Ua{constructor(a,b){this.Y=this.ka=null;this.U=this.T=0;this.G=this.F=!1;this.R=!0;this.K=!1;this.o=null;this.A=a.A;this.v=a.v;this.Z=b;this.aa=a.aa;this.ba=a.ba;this.W=0;this.V=2;this.$=a.$;this.L=a.L;this.O=a.Aa}}function Va(a,b){const c=document.getElementById(a);if(!(c instanceof b))throw Error(`Missing or invalid <${b.name.toLowerCase()} id='${a}'> element in DOM.`);return c}
(async function(){try{const a=Va("viewport",HTMLDivElement),b=Va("render-surface",HTMLCanvasElement),c=await Sa();if(!c)throw Error('Failed to load particle data from "./src/data/particles.data"');const d=await Ta();if(!d)throw Error('Failed to load settings from "./src/data/settings.data"');const f=new Ua(d,c);f.Y=b;const e=new ca(f,b);new Pa(f,a,b);const l=new Qa(a);l.i=!0;f.ka=l;(new ua(f,e,l)).start();console.log(c);const h=new O(a,"Demo Window",{x:80,y:80},{width:380,height:600},{width:800,height:1200});
M(h,!1);const k=new W;Fa(k,"Emitter Controls");const g=document.createElement("img");g.classList.add("ui-window__content__image");g.src="./assets/preview_image.jpg";g.alt="Windows XP Background Image";g.width=300;g.height=100;k.g.appendChild(g);const m=document.createElement("p");m.classList.add("ui-window__content__text");m.textContent="Server Status: Source code loaded.";m.style.color="#4cae50";k.g.appendChild(m);P(k,1);Q(k,"Emitor Settings");S(k,"Emitor Size",0,38,14,1);S(k,"Opacity",0,1,.9,.01);
V(k,"Anti-aliasing");U(k,"GPU Render Mode",["Fastest","High Quality","Wireframe","Debug"]);P(k,1);Q(k,"Save & Load");T(k,"Save Emitor","save-emitor","#73a2e0ff");T(k,"Load Emitor","load-emitor","#84da62ff");T(k,"Delete Emitor","delete-emitor","#e04e4eff");N(h,k.g,"Emitor Controls","./assets/icons/electronics.svg");const n=new W;Fa(n,"Application Settings");Q(n,"Display");U(n,"Theme","Light;Dark;System Default;Cyan;party;Amogus;Sus;nerd;nerd2;nerd3".split(";"));S(n,"Brightness",0,100,75,1);V(n,"Enable Animations");
P(n,1);Q(n,"Performance");U(n,"Render Backend",["Auto","WebGPU","WebGL"]);V(n,"Use Hardware Acceleration");S(n,"Max FPS",30,240,120,10);P(n,1);Q(n,"System");T(n,"Reset Settings","reset-settings","#e04e4eff");T(n,"Check for Updates","check-updates");Ea(h);N(h,n.g,"Settings","./assets/icons/settings.svg")}catch(a){console.error("ERROR: Failed to initialize app:",a)}})();
