var k=(a,b)=>{if(!b.has(a))throw TypeError("Cannot read from private field");return b.get(a)},r=(a,b,c)=>{if(b.has(a))throw TypeError("Cannot add the same private member more than once");b instanceof WeakSet?b.add(a):b.set(a,c)},t=(a,b,c)=>{if(!b.has(a))throw TypeError("Cannot write to private field");b.set(a,c)},w=(a,b,c)=>{if(!b.has(a))throw TypeError("Cannot access private method");return c},aa=(a,b)=>({set X(c){t(a,b,c)},get X(){return k(a,b)}});
(function(){function a(c){if(!c.Da){c.Da=!0;var d={};d=(c.integrity&&(d.integrity=c.integrity),c.referrerPolicy&&(d.referrerPolicy=c.referrerPolicy),c.crossOrigin==="use-credentials"?d.credentials="include":c.crossOrigin==="anonymous"?d.credentials="omit":d.credentials="same-origin",d);fetch(c.href,d)}}const b=document.createElement("link").relList;if(!(b&&b.supports&&b.supports("modulepreload"))){for(const c of document.querySelectorAll('link[rel="modulepreload"]'))a(c);(new MutationObserver(c=>
{for(const d of c)if(d.type==="childList")for(const f of d.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&a(f)})).observe(document,{childList:!0,subtree:!0})}})();const z={J:342,I:192,Aa:10,za:1,na:42,ma:4,oa:.02,Ka:0,Ja:1,Na:!0,Ma:!1,xa:16.667,W:25};function ba(a){a=[...a];for(let b=a.length-1;b>0;b--){const c=Math.floor(Math.random()*(b+1));[a[b],a[c]]=[a[c],a[b]]}return a}
function ca(a){var b=Math.max(10,Math.min(a,80));const c=b*Math.PI/180;a=[];(a.push([{dx:0,dy:-1}]),b<50)?(a.push([{dx:1,dy:-1},{dx:-1,dy:-1}]),b=Math.round(1/Math.tan(c)),a.push([{dx:b,dy:-1},{dx:b*-1,dy:-1}])):(b=Math.round(Math.tan(c)),a.push([{dx:1,dy:-b},{dx:-1,dy:-b}]));return a}
async function da(){try{const a=await fetch("./src/data/particles.data");if(!a.ok)throw Error(`HTTP error! Status: ${a.status}`);return await a.text()}catch(a){throw console.error("Failed to read particle data from ./src/data/particles.data:",a),Error("Failed to load particle data.");}}
async function ea(){var a=await da();let b={};var c=new Set,d=null;for(var f of a.split("\n"))if(a=f.trim(),a.length!==0&&!a.startsWith("#"))if(a.startsWith("[")&&a.endsWith("]"))a=parseInt(a.slice(1,-1),10),isNaN(a)||a<10?d=null:c.has(a)?(console.warn(`[Loader] Duplicate ID found: ${a}. Ignoring.`),d=null):(c.add(a),d=a,b[a]={});else if(d!==null&&(a=a.split(":").map(g=>g.trim()),a.length===2)){const g=a[1],e=b[d];switch(a[0]){case "name":e.name=g;break;case "category":e.h=parseInt(g,10);break;case "base_color":e.ea=
g;break;case "variant_color":e.ka=g;break;case "is_movable":e.ga=g==="true";break;case "density":e.D=parseFloat(g);break;case "max_concentration":e.Fa=parseInt(g);break;case "repose_angle":e.ja=parseFloat(g)}}c={};for(const g in b)d=b[g],f=parseInt(g,10),d.name===void 0||d.h===void 0||d.ea===void 0||d.ka===void 0||d.ga===void 0||d.D===void 0?console.warn(`[Loader] Corrupted particle block found of ID: ${f}. Missing core properties.`):(a={id:f,name:d.name,$:d.ea,ca:d.ka,U:d.ga,D:d.D},d.h===1?c[f]=
{...a,h:1}:d.h===2?c[f]={...a,ha:d.Fa,h:2}:d.h===3?c[f]={...a,h:3}:d.h===4?c[f]={...a,h:4,ia:d.ja,aa:ca(d.ja)}:d.h===5&&(c[f]={...a,h:5}));return c[0]={id:0,name:"Empty",h:0,$:"#0E0E11",ca:"#0E0E11",U:!0,D:0},c}var A,fa,ha,ia;
class ja{constructor(a){r(this,A);this.g=a;this.i=this.g.getContext("2d");this.R=z.J;this.P=z.I;this.O=new Uint8ClampedArray(this.R*this.P*4);this.Y=[];this.j=[];this.Z=[];this.g.width=this.R;this.g.height=this.P;this.i.imageSmoothingEnabled=!1;this.i.translate(0,this.g.height);this.i.scale(1,-1)}}A=new WeakSet;
fa=function(){var a=this.Y;const b=this.R,c=this.P;for(const d of a){a=(c-1-d.position.y)*b+d.position.x;let f=w(this,A,ha).call(this,d);this.O[a*4]=f[0];this.O[a*4+1]=f[1];this.O[a*4+2]=f[2];this.O[a*4+3]=f[3]}};ha=function(a){return a.color};ia=function(a,b){for(const {index:d,value:f}of b){var c=f[3];b=c/255;const g=Math.round(f[1]*b+a[d*4+1]*(1-b)),e=Math.round(f[2]*b+a[d*4+2]*(1-b));c=Math.min(a[d*4+3],c);a[d*4]=Math.round(f[0]*b+a[d*4]*(1-b));a[d*4+1]=g;a[d*4+2]=e;a[d*4+3]=c}};
const ka=Object.freeze({Za:new Uint8ClampedArray([255,255,255,255]),da:new Uint8ClampedArray([0,0,0,255]),Ra:new Uint8ClampedArray([128,128,128,255]),RED:new Uint8ClampedArray([255,0,0,255]),Sa:new Uint8ClampedArray([0,255,0,255]),Ia:new Uint8ClampedArray([0,0,255,255]),$a:new Uint8ClampedArray([255,255,0,255]),La:new Uint8ClampedArray([0,255,255,255]),Ta:new Uint8ClampedArray([255,0,255,255]),Wa:new Uint8ClampedArray([0,0,0,0]),Va:new Uint8ClampedArray([255,255,255,128])});
function B(a){if(a==null)return ka.da;a=a.replace("#","");if(a.length===6)a+="FF";else if(a.length===3){let c="";for(var b of a)c+=b,c+=b;a=c+"FF"}else return ka.da;b=parseInt(a,16);return new Uint8ClampedArray([b>>24&255,b>>16&255,b>>8&255,b&255])}function la(a){return.299*a[0]+.587*a[1]+.114*a[2]}
const ma=Object.freeze({la:[{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1},{dx:-1,dy:0},{dx:1,dy:0},{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1}]}),na=Object.freeze({Xa:{dx:-1,dy:1},Ca:{dx:0,dy:1},Ya:{dx:1,dy:1},qa:{dx:-1,dy:0},Ua:{dx:1,dy:0},Pa:{dx:-1,dy:-1},Oa:{dx:0,dy:-1},Qa:{dx:1,dy:-1}});var C,E,F,oa,pa;function G(a,b){k(a,E).add(b.index);b=qa(a,b);for(const c of b)k(a,E).add(c.index)}function ra(a,b,c){return b>=0&&b<a.width&&c>=0&&c<a.height?k(a,C)[c*a.width+b]:null}
function sa(a,b,c,d=!1){for(var f of c)if(f){c=ba(f);for(const g of c)if(c=g.dx,d&&Math.random()>.5&&(c=g.dx*-1),(c=ra(a,b.position.x+c,b.position.y+g.dy))&&c.U&&b.D>c.D)return k(a,C)[c.index]=b,k(a,C)[b.index]=c,d={x:b.position.x,y:b.position.y},f=b.index,b.position=c.position,b.index=c.index,c.position=d,c.index=f,G(a,b),G(a,c),c}return null}
function ta(a,b,c){k(a,C)[b.index]=c;k(a,C)[c.index]=b;const d={x:b.position.x,y:b.position.y},f=b.index;b.position=c.position;b.index=c.index;c.position=d;c.index=f;G(a,b);G(a,c)}function ua(a,b,c){return ra(a,b.position.x+c.dx,b.position.y+c.dy)}function qa(a,b){return ma.la.map(c=>ua(a,b,c)).filter(c=>c!==null).filter(()=>!0)}
class va{constructor(a,b,c){r(this,F);r(this,C);r(this,E);this.width=a;this.height=b;t(this,C,Array(a*b));t(this,E,new Set);this.va=c;w(this,F,pa).call(this,0)}get data(){return k(this,C)}get fa(){return k(this,E)}}C=new WeakMap;E=new WeakMap;F=new WeakSet;
oa=function(a){a=this.va[a];if(!a)return null;var b=Math.round(Math.random()*5)/5;const c=B(a.$),d=B(a.ca);b=new Uint8ClampedArray([c[0]+(d[0]-c[0])*b,c[1]+(d[1]-c[1])*b,c[2]+(d[2]-c[2])*b,c[3]+(d[3]-c[3])*b]);b={handle:-1,id:a.id,name:a.name,color:b,position:{x:-1,y:-1},index:0,U:a.U,D:a.D};return a.h===0?{...b,h:0}:a.h===1?{...b,h:1}:a.h===2?{...b,h:2,ab:0,ha:a.ha}:a.h===3?{...b,h:3}:a.h===4?{...b,h:4,ia:a.ia,aa:a.aa}:a.h===5?{...b,h:5,node:-1}:null};
pa=function(a){const b=this.width,c=this.height;t(this,C,Array(b*c));for(let d=0;d<c;d++)for(let f=0;f<b;f++){let g=d*b+f,e=w(this,F,oa).call(this,a);e&&(e.position.x=f,e.position.y=d,e.index=g,k(this,C)[g]=e,k(this,E).add(e.index))}};const wa=Object.keys(na);var H,xa,I,ya,za,J,K,L,Aa,Ba,M,N,O,P,Ca,Da,Q,Ea,Fa,Ga,Ha,Ia;
function Ja(a){const b=a.width;var c=a.height;const d=[],f=[],g={};for(--c;c>=0;c--)for(let p=0;p<b;p++){var e=c*b+p,h=ra(a,p,c);if(!h||h.h!==2||h.h!==2)continue;const n=ua(a,h,na.Ca);var q=ua(a,h,na.qa),l=n&&n.id===h.id;const m=q&&q.id===h.id;let v=-1;m&&(v=c*b+(p-1));let x=-1;l&&(x=(c+1)*b+p);q=n&&n.id===0;if(m||l)if(m&&!l)l=g[v],d[l].push(e),q&&(f[l].A.push(h),f[l].F.push(n)),g[e]=l;else if(!m&&l)l=g[x],d[l].push(e),q&&(f[l].A.push(h),f[l].F.push(n)),g[e]=l;else{if(l=g[x],d[l].push(e),q&&(f[l].A.push(h),
f[l].F.push(n)),g[e]=l,e=g[v],e!==l){h=f[e];for(const y of h.A)f[l].A.push(y);for(const y of h.F)f[l].F.push(y);h=d[e];for(const y of h)g[y]=l;d[e]=[];f[e]={A:[],F:[]}}}else l=f.length,d.push([e]),f.push({A:[],F:[]}),q&&(f[l].A.push(h),f[l].F.push(n)),g[e]=l}return f.filter(p=>p.A.length>30)}
class Ka{constructor(a,b,c,d){r(this,Q);r(this,H);r(this,xa);r(this,I);r(this,ya);r(this,za);r(this,J);r(this,K);r(this,L);r(this,Aa);r(this,Ba);r(this,M);r(this,N);r(this,O);r(this,P,0);r(this,Ca,60);r(this,Da,f=>{if(k(this,L)){if(k(this,N)){var g=f-k(this,N);t(this,N,f);var e=k(this,xa),h=k(this,J),q=k(this,H),l=Math.floor(e.o.x),p=Math.floor(e.o.y);if(e.H){var n=La(e,l,p);q.Z=n}if(e.g||e.j)if(q=p<e.C+e.l&&p>=0-e.l,l<e.B+e.l&&l>=0-e.l&&q){--p;q=e.l;n=e.g?e.v:0;for(let T=-q;T<=q;T++)for(let U=-q;U<=
q;U++)if(!(T*T+U*U>q*q)){var m=l+T,v=p+U;if(m>=0&&m<h.width&&v>=0&&v<h.height){var x=ra(h,m,v);if(n===0||x===null||x.id===0){x=h;var y=n;m>=0&&m<x.width&&v>=0&&v<x.height&&(y=w(x,F,oa).call(x,y),y.position.x=m,y.position.y=v,y.index=v*x.width+m,G(x,y),k(x,C)[v*x.width+m]=y)}}}}e.T&&(h=e.l-e.G*e.sa,h=Math.floor(h),h=Math.min(e.ua,h),h=Math.max(0,h),e.l=h,e.G=0);t(this,O,k(this,O)+g);for(g=0;k(this,O)>=k(this,M);){l=[];for(var u of k(this,J).fa)l.push(k(this,J).data[u]);aa(this,P).X++;k(this,P)>k(this,
Ca)&&(k(this,J).fa.clear(),t(this,P,0));p=new Uint8ClampedArray([210,55,55,180]);e=k(this,H);h=l;p=k(this,I).Ea?p:void 0;if(e.Y.push(...h),p){q=e.R;n=e.P;for(var D of h)e.j.push({index:(n-1-D.position.y)*q+D.position.x,value:p})}w(this,Q,Ea).call(this,l);this.ba++;t(this,O,k(this,O)-k(this,M));g++;g>60&&t(this,O,0)}u=k(this,H);w(u,A,fa).call(u);D=new Uint8ClampedArray(u.O);w(u,A,ia).call(u,D,u.j);w(u,A,ia).call(u,D,u.Z);D=new ImageData(D,u.R,u.P);u.i.putImageData(D,0,0);u.Y.length=0;u.j=[];u.Z=[];
u=k(this,I);k(u,R)&&(w(u,Ma,Na).call(u,f,this),(f=k(u,S).get("fps"))&&(f.textContent=`FPS: ${k(u,V).toFixed(2)}`),(f=k(u,S).get("tps"))&&(f.textContent=`TPS: ${k(u,W).toFixed(2)}`))}else t(this,N,f);t(this,Aa,requestAnimationFrame(k(this,Da)))}});t(this,H,b);t(this,xa,c);t(this,I,d);t(this,ya,z.J);t(this,za,z.I);t(this,J,new va(k(this,ya),k(this,za),a));t(this,K,new Set);t(this,L,!1);t(this,Aa,null);t(this,Ba,z.xa);t(this,M,z.W);t(this,N,null);t(this,O,0);this.ba=0}start(){k(this,L)||(t(this,L,!0),
k(this,Da).call(this,0))}}H=new WeakMap;xa=new WeakMap;I=new WeakMap;ya=new WeakMap;za=new WeakMap;J=new WeakMap;K=new WeakMap;L=new WeakMap;Aa=new WeakMap;Ba=new WeakMap;M=new WeakMap;N=new WeakMap;O=new WeakMap;P=new WeakMap;Ca=new WeakMap;Da=new WeakMap;Q=new WeakSet;
Ea=function(a){k(this,K).clear();a=ba(a);a.sort((b,c)=>b.position.y-c.position.y);for(const b of a)if(b&&!k(this,K).has(b.index))switch(b.h){case 2:w(this,Q,Fa).call(this,b);break;case 3:w(this,Q,Ga).call(this,b);break;case 4:w(this,Q,Ha).call(this,b)}a=Ja(k(this,J));w(this,Q,Ia).call(this,a)};Fa=function(a){const b=sa(k(this,J),a,[[{dx:0,dy:-1}],[{dx:-1,dy:-1},{dx:1,dy:-1}],[{dx:-1,dy:0},{dx:1,dy:0}]],!1);b&&(k(this,K).add(a.index),k(this,K).add(b.index))};
Ga=function(a){var b=[[na[wa[Math.floor(Math.random()*wa.length)]]]];(b=sa(k(this,J),a,b,!1))&&(k(this,K).add(a.index),k(this,K).add(b.index))};Ha=function(a){var b=a.aa;(b=sa(k(this,J),a,b,!0))&&(k(this,K).add(a.index),k(this,K).add(b.index))};
Ia=function(a){for(const b of a){a=b.A.sort((e,h)=>h.position.y-e.position.y);const c=b.F.sort((e,h)=>e.position.y-h.position.y),d=a.length;let f=0;const g=d/4;for(let e=0;e<d;e++){const h=a[e],q=c[e];if(Math.sqrt(h.position.x*q.position.x+h.position.y*q.position.y),h.position.y>q.position.y&&(ta(k(this,J),h,q),k(this,K).add(h.index),k(this,K).add(q.index),f++,f>=g))break}}};
function Oa(a,b){a.g=document.createElement("div");a.g.classList.add("ui-window");a.g.style.left=`${b.x}px`;a.g.style.top=`${b.y}px`;a.g.style.width=`${a.size.width}px`;a.g.style.height=`${a.size.height}px`;a.g.style.maxWidth=`${a.N.width}px`;a.g.style.maxHeight=`${a.N.height}px`;a.V.appendChild(a.g);a.i=document.createElement("div");a.i.classList.add("ui-window__titlebar");b=document.createElement("span");b.classList.add("ui-window__title");b.textContent="Particle Palette";a.i.appendChild(b);a.g.appendChild(a.i);
b=document.createElement("div");b.classList.add("ui-window__controls");a.o=document.createElement("button");a.o.classList.add("ui-window__title-button");const c=document.createElement("img");c.src="./assets/icons/close.svg";a.o.appendChild(c);b.appendChild(a.o);a.i.appendChild(b);a.j=document.createElement("div");a.j.classList.add("ui-window__content-area");a.j.style.flexDirection="row";a.g.appendChild(a.j);a.l=document.createElement("div");a.l.classList.add("ui-window__category-strip","strip-left");
a.j.appendChild(a.l);a.u=document.createElement("div");a.u.classList.add("ui-window__content-container");a.j.appendChild(a.u)}function Pa(a,b){const c=a.m[b];c&&(a.m.forEach(d=>{d.style.display="none"}),c.style.display="",a.G.forEach((d,f)=>{f===b?d.classList.add("active"):d.classList.remove("active")}))}function Qa(a){const b=document.createElement("div");b.classList.add("ui-flex-spacer");a.l.appendChild(b)}
function X(a,b,c,d){let f=a.m.length;a.m.length!==0&&(b.style.display="none");b.id="container-"+f;a.u.appendChild(b);const g=document.createElement("button");g.classList.add("ui-window__category-button");g.title=c;a.l.appendChild(g);const e=document.createElement("img");e.classList.add("ui-window__category-icon");e.alt=c;e.src=d;g.appendChild(e);g.addEventListener("click",()=>Pa(a,f));a.m.length>0&&(a.l.style.display="flex");a.G.push(g);a.m.push(b)}
function Ra(a,b){b==="left"||b==="top"?(a.j.appendChild(a.l),a.j.appendChild(a.u)):(a.j.appendChild(a.u),a.j.appendChild(a.l));b==="left"||b==="right"?a.j.style.flexDirection="row":a.j.style.flexDirection="column";a.l.classList.forEach(c=>{c.startsWith("strip-")&&a.l.classList.remove(c)});a.l.classList.add("ui-window__category-strip",`strip-${b}`)}
const Ta=class{constructor(a){var b={x:320,y:300};this.G=[];this.m=[];this.C=()=>{Sa++;this.g.style.zIndex=Sa.toString()};this.H=c=>{if(c.stopPropagation(),this.C(),c.button===0){this.i.setPointerCapture(c.pointerId);const d=this.g.getBoundingClientRect();this.B.x=c.clientX-d.left;this.B.y=c.clientY-d.top;this.v=!0}else this.v=!1};this.L=c=>{this.v&&(this.i.releasePointerCapture(c.pointerId),this.v=!1)};this.K=c=>{if(this.v){const d=Math.max(0,Math.min(c.clientY-this.B.y,window.innerHeight-this.g.offsetHeight));
this.g.style.left=`${Math.max(0,Math.min(c.clientX-this.B.x,window.innerWidth-this.g.offsetWidth))}px`;this.g.style.top=`${d}px`}};this.S=()=>{window.removeEventListener("resize",this.M);this.i.removeEventListener("pointerdown",this.H);this.i.removeEventListener("pointermove",this.K);this.i.removeEventListener("pointerup",this.L);this.g.removeEventListener("mousedown",this.C);this.g&&this.g.parentElement&&this.g.parentElement.removeChild(this.g);this.j=this.l=this.o=this.i=this.g=null};this.M=()=>
{const c=this.g.offsetLeft,d=this.g.offsetTop,f=Math.max(0,Math.min(c,Math.max(0,window.innerWidth-this.g.offsetWidth))),g=Math.max(0,Math.min(d,Math.max(0,window.innerHeight-this.g.offsetHeight)));(f!==c||g!==d)&&(this.g.style.left=`${f}px`,this.g.style.top=`${g}px`)};this.T=c=>{c.stopPropagation()};this.V=a;this.title="Particle Palette";this.position=b;this.size={width:250,height:200};this.N={width:420,height:400};this.v=!1;this.B={x:0,y:0};Oa(this,b);this.g.addEventListener("mousedown",this.C);
this.i.addEventListener("pointerdown",this.H);this.i.addEventListener("pointermove",this.K);this.i.addEventListener("pointerup",this.L);this.o.addEventListener("click",this.S);this.o.addEventListener("pointerdown",this.T);window.addEventListener("resize",this.M);this.C()}};var Sa=100;
function Ua(a){var b=["Left","Right","Top","Bottom"];const c=document.createElement("div");c.classList.add("flex-row");const d=document.createElement("label");d.textContent="Orientation:";c.appendChild(d);const f=document.createElement("div");f.classList.add("custom-dropdown-container");c.appendChild(f);const g=document.createElement("div");g.classList.add("dropdown-button");const e=document.createElement("span");e.textContent=b[0]?b[0]:"Template Item";e.id="palette-orientation-display";g.appendChild(e);
f.appendChild(g);const h=document.createElement("ul");h.classList.add("dropdown-list");h.id="palette-orientation-list";f.appendChild(h);let q=Math.max(0,Math.min(3,b.length-1));const l=[];for(let p=0;p<b.length;p++){const n=b[p],m=document.createElement("li");m.style.marginBottom="0px";m.classList.add("dropdown-item");m.textContent=n;m.dataset.index=p.toString();m.dataset.value=n.toLowerCase().replace(/\s/g,"-");p===q&&(m.classList.add("is-selected"),e.textContent=n);m.addEventListener("click",v=>
{v.stopPropagation();l[q].classList.remove("is-selected");q=p;m.classList.add("is-selected");e.textContent=n;h.classList.remove("is-open")});h.appendChild(m);l.push(m)}return g.addEventListener("click",p=>{if(p.stopPropagation(),h.classList.toggle("is-open")){h.parentElement;h.dataset.Ga=f.id;document.body.appendChild(h);var n=g.getBoundingClientRect();p=h.getBoundingClientRect();p=h.scrollHeight||p.height;const v=document.documentElement.clientHeight;h.style.position="absolute";h.style.left=`${n.left}px`;
h.style.width=`${n.width}px`;h.style.zIndex="9999";var m=h.querySelector(".dropdown-item.is-selected");m?(m=m.offsetTop,n=n.top-m,n<0&&(n=0),n+p>v&&(n=Math.max(0,v-p)),h.style.top=`${Math.round(n)}px`,h.scrollTop=m):(n=n.bottom,n+p>v&&(n=Math.max(0,v-p)),h.style.top=`${Math.round(n)}px`,h.scrollTop=0)}else h.parentElement===document.body&&f.appendChild(h)}),a.g.appendChild(c),{button:g,items:l}}
class Va{constructor(){this.g=document.createElement("div");this.g.classList.add("ui-window__content")}}
function Wa(a){const b=a.i;b.addEventListener("pointerdown",a.V);b.addEventListener("pointermove",a.pa);b.addEventListener("pointerup",a.ra);b.addEventListener("pointercancel",a.L);b.addEventListener("lostpointercapture",a.L);b.addEventListener("pointerenter",a.M);b.addEventListener("pointerleave",a.N);b.addEventListener("focus",a.M);b.addEventListener("blur",a.N);b.addEventListener("wheel",a.Ba,{passive:!1});a.K.addEventListener("contextmenu",a.wa);window.addEventListener("pointerup",a.S);window.addEventListener("mouseup",
a.S);document.addEventListener("visibilitychange",a.ya)}
function Xa(a,b){const c=new Ta(a.K);Ra(c,"bottom");var d=document.createElement("div");d.classList.add("particle-palette-container");X(c,d,"Solids","./assets/icons/solid.svg");d=document.createElement("div");d.classList.add("particle-palette-container");X(c,d,"Liquids","./assets/icons/liquid.svg");d=document.createElement("div");d.classList.add("particle-palette-container");X(c,d,"Gases","./assets/icons/gas.svg");d=document.createElement("div");d.classList.add("particle-palette-container");X(c,d,
"Sands","./assets/icons/sand.svg");d=document.createElement("div");d.classList.add("particle-palette-container");X(c,d,"Electronics","./assets/icons/electronics.svg");d=new Va;Ua(d).items.forEach(g=>{g.addEventListener("click",()=>{const e=g.dataset.value;e&&Ra(c,e)})});Qa(c);X(c,d.g,"Settings","./assets/icons/settings.svg");Pa(c,1);a.u=2;d=c.G;const f=c.m;for(let g=0;g<d.length-1;g++)d[g].addEventListener("click",()=>{for(var e of f){const h=e.querySelector(".selected");h&&h.classList.remove("selected")}(e=
f[g])&&(e=e.querySelector(".particle-button"))&&(e.classList.add("selected"),a.v=parseInt(e.dataset.Ha||"-1",10),a.u=parseInt(e.dataset.h||"-1",10))});d=!1;for(const g in b){const e=b[g];if(!e)continue;const h=f[e.h-1];if(!h)continue;const q=e.$,l=e.ca,p=la(B(q))>210?"#323238":"#FFFFFFFF",n=B(p),m=document.createElement("button");m.className="particle-button";m.textContent=e.name;m.style.setProperty("--particle-button-base-color",q);m.style.setProperty("--particle-button-variant-color",l);m.style.color=
p;m.style.textShadow=`1px 1px 2px rgba(${n[0]}, ${n[1]}, ${n[2]}, 0.6)`;m.dataset.Ha=e.id.toString();m.dataset.h=e.h.toString();m.addEventListener("click",()=>{for(const v of f){const x=v.querySelector(".selected");x&&x.classList.remove("selected")}m.classList.add("selected");a.v=e.id;a.u=e.h});h.appendChild(m);!d&&e.h===a.u&&(m.classList.add("selected"),a.v=e.id,d=!0)}}
function La(a,b,c){var d=a.l;const f=[],g=a.B,e=a.C,h=[-1,1];a=(p,n)=>{for(const m of h)for(const v of h){const x=b+p*v,y=c+n*m,u=b+n*v,D=c+p*m;x>=0&&x<g&&y>=0&&y<e&&f.push({index:(e-y)*g+x,value:new Uint8ClampedArray([227,227,227,180])});u>=0&&u<g&&D>=0&&D<e&&f.push({index:(e-D)*g+u,value:new Uint8ClampedArray([227,227,227,180])})}};let q=d,l=0;d-=d;for(a(q,l);l<q;)l++,d<0?d+=2*l+1:(q--,d+=2*(l-q)+1),a(q,l);return f}
class Ya{constructor(a,b,c){this.V=d=>{this.m=d.pointerId;d.button===0?(this.g=!0,this.j=!1):d.button===2?(this.j=!0,this.g=!1):(this.g=!1,this.j=!1);try{this.i.setPointerCapture(d.pointerId)}catch{}const f=this.i.getBoundingClientRect(),g=this.C/f.height;this.o.x=this.B/f.width*(d.clientX-f.left);this.o.y=this.i.height-(d.clientY-f.top)*g};this.ra=d=>{if(this.m===d.pointerId){this.m=null;try{this.i.releasePointerCapture(d.pointerId)}catch{}}this.j=this.g=!1};this.pa=d=>{var f=this.i.getBoundingClientRect();
const g=this.i.height/f.height;if(this.o.x=this.B/f.width*(d.clientX-f.left),this.o.y=this.i.height-(d.clientY-f.top)*g,typeof d.buttons=="number")f=(d.buttons&2)===2,this.g=(d.buttons&1)===1,this.j=f};this.L=d=>{if(this.g=!1,this.j=!1,this.m===d.pointerId){try{this.i.releasePointerCapture(d.pointerId)}catch{}this.m=null}};this.S=()=>{this.j=this.g=!1;this.m=null};this.ya=()=>{document.hidden&&(this.g=!1,this.j=!1,this.m=null)};this.Ba=d=>{d.preventDefault();this.T=!0;this.G=d.deltaY};this.wa=d=>
{d.preventDefault()};this.M=()=>{this.H=!0};this.N=()=>{this.H=!1};this.ta=d=>{document.querySelectorAll(".dropdown-list.is-open").forEach(f=>{var g=f.dataset.Ga;g=g?document.getElementById(g):null;f.contains(d.target)||g?.contains(d.target)||(f.classList.remove("is-open"),g?.appendChild(f))})};this.K=b;this.i=c;this.B=z.J;this.C=z.I;this.sa=z.oa;this.ua=z.na;this.v=z.Aa;this.u=z.za;this.l=z.ma;this.m=null;this.j=this.g=!1;this.H=!0;this.T=!1;this.G=0;this.o={x:0,y:0};Wa(this);Xa(this,a);document.addEventListener("click",
this.ta)}}var R,Za,S,Y,V,W,Z,Ma,Na,$a;class ab{constructor(a){r(this,Ma);r(this,R);r(this,Za);r(this,S);r(this,Y);r(this,V);r(this,W);r(this,Z);t(this,R,!1);t(this,Za,!1);t(this,S,new Map);t(this,Y,0);t(this,V,0);t(this,W,0);t(this,Z,0);w(this,Ma,$a).call(this,a)}get Ea(){return k(this,Za)}}R=new WeakMap;Za=new WeakMap;S=new WeakMap;Y=new WeakMap;V=new WeakMap;W=new WeakMap;Z=new WeakMap;Ma=new WeakSet;
Na=function(a,b){const c=a-k(this,Z);c>=1E3&&(t(this,V,k(this,Y)*1E3/c),t(this,W,b.ba*1E3/c),t(this,Y,0),b.ba=0,t(this,Z,a));aa(this,Y).X++};
$a=function(a){var b=document.createElement("div");b.classList.add("debug-container");a.appendChild(b);k(this,S).set("debug-container",b);a=document.createElement("div");a.classList.add("debug-info-container");b.appendChild(a);k(this,S).set("info-container",a);b=document.createElement("div");b.classList.add("debug-info");a.appendChild(b);k(this,S).set("fps",b);b=document.createElement("div");b.classList.add("debug-info");a.appendChild(b);k(this,S).set("tps",b)};
(async function(){try{z.J=Math.max(40,Math.min(400,z.J));z.I=Math.max(40,Math.min(400,z.I));z.W=Math.max(4,Math.min(1E3,z.W));Object.freeze(z);const a=document.getElementById("main-canvas");if(!(a instanceof HTMLCanvasElement))throw Error("HTML element 'main-canvas' does not exist.");const b=document.getElementById("main-panel");if(!(b instanceof HTMLDivElement))throw Error("HTML element 'main-panel' does not exist.");a.style.aspectRatio=(z.J/z.I).toString();const c=new ja(a),d=await ea(),f=new Ya(d,
b,a),g=new ab(b);t(g,R,!0);(new Ka(d,c,f,g)).start();console.log(d)}catch(a){console.error("ERROR: Failed to initialize engine due to data loading failure.",a)}})();
